#include <list>
#include <vector>
#include <pthread.h>
#include <cstring>
#include <jni.h>
#include <unistd.h>
#include <fstream>
#include <iostream>
#include <dlfcn.h>
#include "Tools/Includes/Logger.h"
#include "Tools/Includes/obfuscate.h"
#include "Tools/Includes/Utils.h"

#include "Tools/SOCKET/client.h"
#include "Tools/SOCKET/IncludeClient.h"
#include "Widgets/ImportWidgets.h"
#include "Tools/DrawTools/Draw.h"
#include <chrono>
extern "C"
JNIEXPORT jstring JNICALL
Java_com_ashu_Menu_imageBase64(JNIEnv* env, jobject thiz) {
    return env->NewStringUTF(OBFUSCATE("iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAYAAACLz2ctAABkiUlEQVR42u29d5he51nn/3nKaW+bd3pR77KKS+w4tlPGTsPpJKCEkg0EWAMLWX7LUhcWRWSXztJbILCQsBAr9JaEECwnIYkduVtusqRRGU2feeupz/P8/nhHieI4iU0csMzc1zWX7BnpnXPO8z13+d4N1mRN1mRN1mRN1mRN1mRN1mRN1mRN1mRNnrYcPHhQ3nrrAQWItaexJv+24AN54b+FWMPfmny+iMlJ9OQk+quhnQ4cOKAA3vGtN77hbW/c/2fAyOqvkWuPfk0+H4k9+IlnDnwoEGzsC77je157mXv4w7e4N7904h8umOS1J/4fHG+rX95Lrxr9yckrR38UetrqGQKhcCD29rPhh9+0f/G1m5X9m/99Y/bO/7TDbe339j/RNK/JF8pz+uEcOIAE4XZW+IWvv3HP//y+b73pp/YOHf4jIDh48LPg/Io+X4C77gX79m9f1z9Qq0Xm3nuOybTZdFfs3b0L4NiBA18Vh/AAKOe+8ntYA+CXvrav5PrE4cOYyy/fMvK83UPfvq6aFq51Kvmp//HGb9o3rL//0CFsD6D/ern1VizAjiuueuDEbLuolHy10Mjk9Iq2Ud/IXQB7Dh92X41ncxiMEDjArQHwqyN29Uv+KwMDCXDVpo07NowNlR85PiPufGDBS5OuqZSCVz9D/qQ7cAD1Iz/73jMzy62/yJwQJ885cXq2eM//+7t/OnHgAOpQ7x6eQaoHCdhNkXrTDbuGPn7TNZt3XcrW7Fl70aMee0c9bx9g/zV+1OHDh61ziG7qP9Ry/uMf/fRpdfcdp83v/e5HlJD6owBzc1+5+TrAAQAXt1WeGUtYgoHByp98NUzjQZCHDmH3jlR+7Nve8vw/+8H/fMMLfdu+GeDg5BoAn6mgAWDg9S/Zd/vN12+4b8f6yhsPgT0A6ml+lnvnOxGHP/zhpfNZ5esrfWPNINJ6YHRzJyv8PwLEkSNfsXYSbz582Lxm//5+59JXLjeWnUkLTCGu6wF8Ujyj4AP7sqt2Xz9Wlv+rpldyXzYLl+Y3AOwduTRN8bP0rRlPbJEkozUrKsb9+bXb1v3oYTBPF4SHDuEA8Vf/+Il7F5txK8kyWYm80mte9dJXAu7gwcmv6P4PTk4qQAyMhG/VJh4SSmTKaTwtrwfcyMjIMweKyd619lXka3eNRy6eb+cf/cd79fj6TXMADz6DYP8PD8DLL3+ZODczF3ztN7zUfM1Nu5yNl3/8uut2rDvc86ee7oN2+7fvWGdsVsU5NzNzRuTF4g/ceuutEdxovyJTeeSIBZxP89uyJCYKlCpsjsuTl7xo48b+w4cPm2fKFB8bOeIOHjwoV5YX7ixXhFhotUpLxfBipb711wCxei1fVHt+tUj45xoA3cGDSM8rZRObthy/686HlGkt2TBS0nSL8mrE93QeogAweXdICFdDCJZbHdOaP7t15oHb33ro0CF78OCk4l+Z/TgE9u2vu/y12qRXGtu1gSc0ylpt83rfaHTt56igr1z27JkUhw4dsi+74UXPC0sVHp1zxz788YUrf+P9f/kowBcJdsSFnx05QvFsjJiffRrwEBw9+u4i6xv5xg/efu4fH3l4UY1VxdKd951cWuW93NPgygSAJ/IRiSAz0hVSifMnz9j2/Mn/8TO/8zN9x46NuNXPfZqA2OOAwMvyn+82mtRqnpPOEEWBlbbAE/brnyk/8JZbrvYOHTpS/NyP3PLKuHn6fx579CQmGPz7c/HS2Vtuudr7Is/ks89q//ry/is29H/ntZdfvuUZJOGfmwC88Ca/7/A/nvzbu0+/cnznnvdevm1i4nX7Jn5RCNytT0OjzE32HrSWYqsSgjSzNnNCLreMWzl3fHN+7x3vPHz4sHnnOw+qp+eOTepDhw7ZN714+2vLzu7GpqZUChXOIZVUwhkC7KvWr18fHTly5CsywwcOHFDvfvfR/Nvf8pLLWnOP/8mxY/caK6v0D4w+DMhHHqk8KfgOgrjuuuui67eP/9n2Qe++F14x8duKZMszqZWfyzSMu+WWqz3nEH0j6/9kYSVj347Bt12/ve/r33IY08u/PnXxXXGldJbcOpxz5Fh56rEp6+LFW972uhfu/cmf/MlilV97SvI9q8HF1tH697Sby65W9ynyJtLTCJsJ4WkrSdftW19++Vdy4AdBfuADHzBbR/r3j/jmQ+eP3z+w3MgdQUCpNvgoYJ8s0JmcXOUfl8/+BM3FN73oii1m27qB1vHjy8cAbj38zHKTzxUAislJ9IVId/zdR40QuFrf4D2zXd3JVlZ46ZU7f9VB5dY9B5+SL3jbEQwgpeAFhQXjkNI5CpuL+Y5xS7PHS5v75Xudc2rv3gNPKa114MAB9ebDh80tb3jBWwIR39RpN20UOoUt0MogXUbkSetMTkm7twDuX2mG5d5bDwjn3MZXX7f971k6v+HUmQUjpacCv5SksVvouQJfmGkZOdLzlUsqff5gWZjjp86rR08386v3Xd39XD3GGgC/QOsdOUJxGAwgDoE9ePCg/PFffvf5ifENtz801XBjtWj87Tdt+zVx6JC9dTXT8WUKX9zExES/EG5b7hyFcUKuOka5QD3y8ExRr2RXvf1rr7zlzW8+bFZplS/5mbf2fL9wrKredf70jKvUpPBkQqh8PGXxRI4nC2Vs5kKTvXr/unXrjxw5UjxdM3zLLVerN7/5sPm2m6/51eFyvP6Rx8/mcSFkuVwRWgfpuk2bZi6imr4gSQ24oWogRtatUyea/h3n2+ZtH7zjg82DPD0/+j8CAAXA1q39ffs2j3znvm0T138u2r1NAqxfV/lwpb9PfOLovdnV+8a/9cU7B1/6lg984Eua4gOr97YhzCcDz6/EhTUaJZQUWOconKWVSXXPvcft1TsnfmbraHnknbfdZr5U1uXg5KQShw7Zb3vljkNFOruj0+jYoT4pBTm+rwi0h1YSSEUopVGu6N+5rvqGnnZ/6tH2LVdf7b373UfzN71kx49tGTFveODBR4rlHC9zzpXCEiDP/vWRhQ5PAqYDB1CHDx82V22auL4cll7aKNQHPnTP6Rf89cce+LsLL/ZaFPwEfwVgcyX4xivW6d8e1fG/XLN14gcBcf5v2wKgNjzxoeHxkezRUw3VaTh30w3b/9A517fnS5jiCwGItLwK40ReGCe9HIEAJxASpOfE4ycX3fLM+doPfMerf1sI4W7854PyyT5zchJ96MiR4oV7112xdbDvB6aOz5hqv5WBdijlYU2OzS1KRjhnqJQDGXc76CD9VsDdeOON9imS2/rdR4/mX3PV5v90zea+/3XyoUfMSssq5xxK4pRQIPXisWOHs4NfeJ2CXmqwum3Y+79Ir2uDif/mei+AXqNhnkRuZBKAsbFR84J929kYpVR18Q2AHX/tUQOI73znux8S5cFjY2OD6q47H8m3jfatf9P1W3720KFD9ouYTXGk5/95SosX5UWGtE4q4ROpkKpXQZje2Wlfq3+67W4jO0tv/NG3v+ydN910qPjM79zyeaTtAVAfu10UNWoDr37+xt9qL81IikxsXOeJIHBYU/C8a/Zww4uvIs1ihDBonUsplPFtfs0rdo+88dChQ/bLBU8HV0F+3fahyRdeWXnP3OmTZnoWiZRC4vCEdFIJoig6dnF25OKX+fDhw+bV+9b99JahcKcLy+/5iyNHzr5zclKtugGsAfCJtMuRI8aByPt2/sn9ZzvvD/sGXTVQu7aM1Z5/6BD2HTff7FtriMoTn6hWSliXik987LHiRdds/s7dA+VX/OTttxdPkqITAM/fNrrTU+xO0tQpKaSwMNIPr33l5ShjwDkQIGSg/vpDH8s3DNqD3/Lyy37smu98d+7crXJyEn3L1XgfAGOdq3zDywfeT2f++mOnzpmd20pyqOYoRZZ61Wd81GPrlhLj41UKm1LYLqXII28mDA6UfrT3rA98KUugDx2h2DniXf41L1z/F8l8wzt2uityLxdKGawt0EKiPU3ubPxk9YFHjlBctWH0desGS/8lsTpTfRt+DxDHnsmU4HPQB3QC3OHDh9u/+3dHv2EpnPj6jRPro219pd8FgoFq1QGMT1Rvk0oRRVKeOndWNuY67hU3Xv4rzrnwwK0HPo9cnexVhjhPujcUWUJRFEZqiw4gTxKEWWJidJA8sygpEdrQTJX3sY/cZb7mpZv/1/d983X/nxBvNkeOiOLdR8kdbHjLNYMfHKu4l3/q/lPFFbsG1ZVbfAbLgnKkqJZCzp+aYvrEcQZqIRKFNSmRl6vUFMbT9vk3XjbyusOHD5vVlNgTfD68I7eLYsTj8gOv2PMRrxv33/XQsrXGyhCHKSy5hWzVhibd7InnJvYcxAGVbRN9vxkpQ6bCT73nT//8voMHD4rVlOAaAL9cMHJwclK//0Of/nOlgg/uGKxece3GgR8+dPhwBmCUeNh5JddKYjk8VJJ3fPIhu35AXfbWm/b/7ze/+bD5515KTQJy5Ajuhl27qsbwvd04cw6UEA4tBVJLzp6boxx5pIkjyzKktpQ9mGl48rYP32Nefc3EL/3sd15z5IWb3fe9ZHPw02998dBdoyPBC+97cMZcs7emv+aGOsP9knKoKKwBAdY5kJp2nGAKg7TgRItyoEXebLiJ4covAvXbbvs8HlO4Ww+odx8Vecm5K/7rt+77q6FAD3/6nlmT21QGUY6nHJWgSpFJrNE9HtOYL+T9DmFfsnP05yf61Po0L0R1cPBXwbH32DGxVozwFDXhsZERdxBkaXzrj+q+/mSs7P3olSOVNwC06T/rhZXZbpoLXxfO0VWf+eQjxc51g9//sn0Tv3TToSMFYA8cQBwGY237ndpk46aw1jojrLVYk6MD6HRzQi/l+ms2MjJQJ+86lCzQfkc8eryp/viPP213jo+85Od+6PW//C2vv/xHRn05dGpqwb78ZWPq629eR/+AYWjTEFuu2s/YugnSPAMlSLICpRVXXLWN4aEyWuZ4USybHeMqrrvtm1649Q+EwB0+jDl4ECkETrz5sNlQct/yv7/7uo9PhLXNH7/jnE2KTFUCR4Bly8YxdmzfhClYLX8WYO0XmN4NA8Er926b+C6bNJzXP/ZYubT5H9xqudizGYDq2XQxx44dc99z4ID8vvf9ycxNL756l9dtX91Ni8tPTXR/78gHboyv3Hn8a7uL8xsDz7NSGrmwkMtuu2G2bRy4oc9jqwzCOz/2qR9qXbvt4e8hT96VJJlJ81yWfC0mxvrZsnErWbcN5PglRehL1o2NcfrsAghHpZrjh5blTiHuPDplph5btidPztssy8W3vGmHfOmLyig/JYjKxHnAgw/OUg0HUUqR5i36BgYZXbeDooCJkYi43SIzhtRqsbTQNMP95T37tm/YOjiy9c7/+8dnm0DwbTfv+6l3fPNLfr5IrP8PHzlu20lDVoIMzxP4ImR0bJhHHz9NK7E4IexQX1Xmwv/UQ2fmPjRSLus9/2XeHjlC9aYrtvz5WN0bkHkmqoMb/uBd//fWv+fgpD5yZMo+mwGon20X9GCP6BXlgf5fyftHDgwuN/e8qBh+y8c59F7rrj1nkDgLURBQLsOZ8w3V7hi7fjh4W1knb1wf/ca5OMt2Z8bSTAulnGN8fJwkabO80iZUZfJ8ibmllIX5FcYnElSgkL7F82CgIogGHbbIVeTNs24kYPLFG9mxQ5NnllKpiskdc+fn2LGhyvTsEr4G7VdQIuS+ux6gudJl/USZUqColSSFyziXWXVy6pzZuCF5267Bxuuv/8b9J7dtWN/X3x9sffC+4+5TR0+SmVRWJGhn6MSOgYF+zs3OEaeGwjik6kXcKNM7t1pTHTpEdt3W/l/aMzG06/y5R/MNm8a9E6em/qz3NI88q8H3rNOAvRK7I84dPChv/OlfmX7Z8/a8XKWdTc1OfPmJpe5vXb9v556FmXM3bhyOrMTIpWYOJc1cKxGtNkbYILTGDMUmtyudTCAcgScwxjG/0mRlpU3oO8qBR6OVk6LpJDFKWMJIUg4EJWWoh4KJ/oAdG0J2bQkZHvCoDZRRgYf0HF7gE4aKgcEArQVz8wv01SqcOHGWUmgZHwooipg4zXA4fCXR2tLNney0jBmIgtKOzRPji/NL/R/+6EP2scfmZKATEemcwXo/E+uHmV9oEIVl0iJhqZGSFmCdc7VySSY57cdmVt537Gwzv2xY/+D1e7f8UNpsZpWw8HO//OC7P/zQoYMHD7pDh579ANTPxot6Zy8D4vyyec/IusEbp9sr2/eP+//dk+WGMAKKAokjMxlOCSqBZKHRVucaiVNKOkMhpS0oRQorDcvNFZyUOOOIs5zReh1pMxApSoEnLJ4UKGTPKRYOrS2eJ1BaoEsSEZYQykPqHOegLxpEGEN/ASMjVcKwTH89INAKV+SAoptK0tygENQ8TdYPc41MnTi37B4+eZfrJB36IiWH6wpnHYWRDE/0s7C0Qrnahy+h1c5QKqBcEqy0uiLLCqxUuxDS7ioHX3fFlvpPl7U0p1ZWxN4d/Zxeyj4ApNx2m+ZZlvW4JDRgTwtOOefgN9438tjesfLbZ2fOVzqx3i+UUmmnsbsWCixaZE6C06RZhtCCOM2FpxHVyAdre8lgLEIKnHNEQYjnWQLtuGz3XuYW5sEZhJYEvsZTEChDGGiq1YCBPk3fgEf/YIVKtYoMPKTno5VGSg9jNcvLHQb6atT6AsChpYeTFmsc3bggzSyZFRhnUJLVMMKIgboS/SUlBsoSX0M3zjFOMd9ocPpcg1IQUipZuonE9ysImdPqFCIISkhR1EYr0ZVjffpHdo4PeefOnmNsXUU1UyVWUv0Dx04vnL9xaoojl0DL5rO2HIvDB+Thw5+KM82RPTvXIdN4pOytfK2nHNVKSUphiZOcJLMIIRHCEQSKSiTRIkdKi8WuBowCpRTCSYTw6GQpDz72EIVxKKGQVuAKcNaBgjCQlDyo92vG19cYGK4R1CKCegm/FqGrJXStQlApkVpJdcAjDAKcKYGUDA7XiMo+vu8hpUAKAVJgKfB8Qa2iWFcXjNQFSlqywmFQJIWh1U3xtERSkOWWpHCcm5nHSR+nfJbaMZiCMS/52omByD99+oTbvVvRbXdEJ1Mn7p4pHhC9uspLoklJP1sv7PDh3p8PP7b0Z6++bv03Hv3MIzYoCucLK8LQ0I4TrDOkucFTgLAICQqF7/kYp2inGdY6hLQopYnzFGMgixRZ1sTzJUIJtHQ4bRBO41yZ1IY0M59zCxUSVaO0EKJLFvwcoRUIRxjkVMoaV+rn3odPU7QUzmjqA2WSrE1hFXluybKCLJcYp7AClJKYzNDqCoRwOBxJbskc5A6cUGiliHxJN8lYbKSgPDpxjnHQTTvEpkI50KbRWJH7dmvhS2HyVMmw4n/q+PEH0oOTk/rQszT1dskA8M2HD1sh4P/97d3/fNVW3T7wmudVbjt63gXaJ5QW4QSB1nTTAuvAGElROBpZgZYOa3rEs+f5+L5CSIcvwNegNAzWS5RDQS3yqFdC6n0lgkCitcIPAoJyT8OpShVVDlC+wit5eJ4i8CV+aPEDS3mizpat63FZSp4mLC4uEbfLeKFFVxKqCy0W57usNDKyVkGRFKQZuMKipMIUDmsEWAlOYK2hr1ql63KacY4VAiMtnWYbITzKnqbbarNgArWubhkoV3jgpGGgr8ZsK7mTS0z0s/janH3/ASXefHgpzsWf1EX+HY+dXLTr+kPl2Q6+UvRVayx1W3SKApMZysqnVtJEvkcUBkgs2JzMFmTWgpBILfA8hxPQySVJIVhsJ4jzRc8jcRYlBVJJpNIEQYj2DdoXeKHG1x7lQBGULOWKoF6tUauGBKrAZCnOCiQKJTQlv0J1fYUd6wuSLGelkbCymLK0nLDQzum0U1Jn0EIgHJjVa52ebyA9QVjycSLDGoNAoIShL9KYQmCzlGoExihana4aXRflZ6YWP7SaX7drAHxGzHDPDj96pvX+bddU//O+9YZKKUUosIViaW6RihaMRT6BriHQpMaQ5YZOt0uaGxJrKZxEaA8tFbKX2EN4CmsFGoGSBk9bAg1lXxP4Hr4n8D2F70m0H+AFilIlJPR9BAZrErorXRrz5+i2II8lrXZKWkiSRJCbFGclUoL2HKVAEXgWrcHzFFL0fE0lLb62KM/gJR7tRNOShiy1JFlGmliEcAjn8LRAKUteOEqeYGwgoB0bW/ED6TxO3v7YzGPOOSGEWAPgM2OGsULAe//27D1Xbto4/4pr+obveaDhZmcQSWyZGKqRkxOnlkY3oRU7DBKjBEIoCqEwWuCcxVqLcgXO5eTG4DqWasUj1IbBiqK/oqhXJbVIUgqh1ucxOlJmYl2VoeE+yrWQSr2MLpUQKsCYjCItKOKUIiuI2wXnT8+yOJ+xtJzTaguabUejbWglklbH0IklncxhHDirsE5SWIGzBoEFl2OdQytQ0sMYiQoFeVFgTE6RWVpaIYQkLAnKUcDiSmYH6jXZbuf3A8Xhw29W9KrK1wD4TJjhj/7EpL7p0JHFx86Kd+dS/Zi0gRkYKutkscPSSkI7FyROYIVH4UM3z4gLg7MOUzhEYUA5hHBUhGRgIGJgrE41DHj4sbMEvsdgvcTESBlsE2GhXKlSH6wTDJTx6jWiPvCDDERIO84oXEpfTaKsZn62YLZp6TZSNo0M4avz1EqWOHG045z5hZhGW9JJoRVbVjqWZgxJqrC5wFpNYSXWKgQSh8W4HIGlcL3AqhR6aFlCWDDCUBRtAiXRfgiuoNLvc3q2cxfAg79x+JKakKCe7RfYHZkSx46ht5bTt73gspErMh26+04tyemVhI5TOC+gKAydOKPVjbHWoqUijjOMNYwN1iiVQrIkZmwwoBCazAX857feiGcyTp6aR3oFUaiolKt0WgV+EKJ0QBw7pqebGFdmbMMgxnY5dXKJIhcMD/dx/IE5br/9NH/7L4J7HxPMzZxmdMAnS7ukuaVcrdOJU7ppF0SOkzlFkSNcQeDlaJEiXYJzMYVJMKanAS0SJzRKhVipKazDmQItLAPVkKF6jXLgk6aCqAxBtSY+eWzpf51bTk+NXIs4duzSmROjnt1T55G/+ZvYr71uyzVvetnuX3vk8bP2Y3fPqswqksIRF4ZWNyaOMzJjcFIx2BcxVK2RxCmJMSgpKJwlz3NGBiPOdjLUwGXMHH+UXetrTJ07h5ICTwmEkCSxY2Q0ol6XDNZgsGrotju0Y8vIxCDtVovNW9fjq4L77pzh2OPz/OMDLc4vF8h4jvXDilJgiROYO9+lsII4S8lSh8kV9b5+qpUaxjiMMfieRCgHzmKcIctz8ixBAd12hzx3CKFQWuKU61XemIRKqAgrZeepQs4tpnN/cVf0g9Asjh27tKLgZzUAR0YOyGPHjrm3fM2O/dPnlt/6L3ees1vGBmS9rCikR2OlA9LDICgMWGfppDnOSvLcoD2FLQrSLMM5Qb0cEgaC0yfPU/JipIlppzF9UUgpimivtBnqU1SqOdZ18WVBtWSZGK/gBYp2AtX+KrgO5Wo/s+dbLM+1SY3E5itct3OUUtBhYDAgbRW02wVxkuOkwvcrDA2uJ8t8Gs2Ubqeg0UrJcCjtkXQthZE4K7hy32Uo3yOJU4q8oCgy8iLFOEfkeygB3W5MITqUI01Qrsogkn9xcmZl9iDISyEDckkA8NixYxwEOXfZ1oWpU8tfe/Umb/jq7dIWzhMn5gqqfXUWV1YorENJnyzLscYRhiFOSKrlCrWyD8phhCHPHPWKZqTqGKgK5hdj0ALhDEWW01/3GBkWRFFGKfAoRREjo3VqVcX4eD+lmgZyymUP31OMjvSzPNdgsOyzf2uNiShm384hHAlJDFp7eEFIqTyItSXm5hbodhtkSUySJ2TGkubgnCRJCtLcMTzUR6VW4lxeYqXdxqfA2gIvkCgsZW2plTR9FQ9TxCJtxcXIcC2sj20++qn7T9194+SkOjI1ZdcAyDPVtIT4hftPxwpuv+GykbfvmsjVmTkr7jjZpFLvI00S4iSnUqoQeIpa4KMCj+W4y0qzSZZmKK0xxtLJc7pxjrCCdjNHK0ngKULtUa2EBF4vYnZWYW1AXmgKF2CVppVYUqvw/BKgSOKYOG+xflOFwZJjuE+zd+sg2mtTmJy8EBRWURjFykqHOF6mVEqJIostUqwQWBxpJoiTHKkVuRX4vod1Bfc9dh7PE3imQAmJpyXWWEqhT6AU4yMhmzePubnFVBhVETNL6S8+eHphauTaqUvKB3y2R8G9Id+HD4tX3HDDxB0P3aGHgpD+WonAb3D+/AzkvYqWRrNJGEUoLVhaXCGzFs/zcIBNCmpBQFipEmhBFFqiQLtS6Ai1oOR7lEPtevV7IUHoEVV9Vy57znqa5SRCOw/f+rQyTeA7hHLCkAthBX0DdVSSsdDtiiQWdLsB7dSIlVZMs9nGGoWvIO5kJLkmzUNwBiUdUaDIDeROIBQsNVuAZEufT1EYUgO2gCzN0VpQGEW7kxN3JZ3EukzV3INnOz9820Onbj8I8tDhS4eCuSQAuGfPnABctey+WY6O6FbcKCrMyf1jIQ/Od1lKLEJKosAhizY4j6Gyj9LSCe05JZTzpHFaWpTIhNL0ChWKRCUdQaYhKzRZpkVLSpaaHSLfp1wKqfdHVOshYWrxSyEoj8DTCC2JgnKv4CDy8aWANCdPm+RFhzwTJIlxJlc2i1PSbuoay22ai12xuNRhVsQy6ySI1AlFgScdRWoRRmAymJ5bRmufuGMwziKlBCEIfQUup6+iqJQi9+jxJen1DXceOvP4b6w2nbu1VNwzLbf1/ui4zszUyWk2763Q9jLidofICNZXSwTKukIqm1lcmhTk1qpOZgR5JnypyLVEKomnQFgBmcTi4Zx0BiuEdC2h5HkplLOFy51JC2y85NE8bp0rENY5ARbnPG0pexInxaDUaqJUEaVS5DkNfcLIDVoqfE+mQqn+UiBVKRRUK5JypPAQ6CBkaMQjiiM6rcwl3dS2UuvasRXtthGt2IjFzIh2Oyc3GidB4QiUQGIolzRhJOmvB9x/YoVyzclv+trX1H/pd/7uwqSENQA+s07gjZYjRzg51fjLTRuHvw/n1EMnFZFfdptqienGRjQzo2JjVKY8bBDgUHhCJFp5UxL5oA78R9Mil0Lpe6RUjW7S7WzZevn91TDMH5iZEXfcsakDHzAA/f1b+rRZGM6lzGuRGfIlW42wVWec8oWnySTWgrV5UJg4T5x9JE1TXILWghXhaRP4+sXSMVNV0YqCisRuCCMpPMUVgZYjUrMr9OxY6InAk1YpaXvbdCRUfUGkA5N42nUzJ+JcyiQ3AtMj15UEJUA45yZGh8SK0Q+ffVlpht95ds184WkOBX9WX+PBg4hDh7A/9ZY9D20O892npov80XML3nySkQqfFG9FSfWQr/1PWj94QGr1oMnShT3r9pz7tQ9+MP0Ceqcv2Br5aqen1JCQZtyTaotF7NZS1n2l1gth+7UvReQFyhQFzhmiMEJKiRQWJUAqhbWWuMgxxpLECc65Je2F3TwryiBO5a5oZrlbwvFonOdLxunHjPAes4XMPc+T6/r6rKW707fFfllkk9pz49IWl0mM1kIgrSM3lsw4U1gBAlEpSTlUk2wZCwujKvqOx4v3fOiBM98xOTmpj1wiJViXlAa89dYD8s1vPmx+7vuv/J9X9oc7P/2JM/l955reivEbpjz8Z4UQR7qe949Hjz58/on/9p/uPw3AhsFowlPyRqnk13laTfpaDWolUFKgJGglkVIQKEE5DBHSobXD14GVwlmcxQ98hBA97cNqQztCqMAXWmustdL3goE0zQfiOKUoiv68sMRxQpEXZMbSzQqS1JLntPKsc7qx0jqeFMU9S4n9QNrJf9/r25i+9rV7zNS9D19VdDuvUFa8REuzV8tiILAFwhpsbmyeCddOlOsbgL6yXBI9toAjwJoGfKZ3Cwrcvg0b+7/ppRunZh++v3r/PFAtv09F4//7w588+vAT5guqdhtx9Cj5pr5gswjl65QU+5RUrw88NRZ6Ck9LlBROOmejwHeBp3tmTUtR8TyRdLqiNljD8wSBJ0SlHCGk7BUzaE3g616xgNaUSiVK5TK+52GsRQrp2u0uK40GjZWWW41HXZpmLkkyGq0OuRHKWSmctbS7Gd28oNtMSJa6hSmFZzvWfmClG//+UsZDAPu2bBmte/n10uZvwuQvUsJs0Tam5Atz5Z518mzbfeo9Hzl5gzt4UIpDh+waAJ/563P7N+7vv2Ji5VQ7WS6W5NB3337XqVu5aKbK6iCiCwMmzdaR8suU4E98Xw5LLfGUwve0CT2JJ5FaKREGPpEEqSVRGFAJIjozC/QN1dH9EQpHGCgq1QjP99BaI6VESIH2PUqlEpVymSiK0ErR6XSxzuCcY35+kXarDYUljlOwkGYp7XYCQpOmubMmc0lcuG5cuMZiR7XOLgk51EdHWOI0Jc7zv84L9wsnV4qPXbjX8fGrS5trsy/2bfrtMu8eGPJSNl62hfumzTf+42dO/OmBAwfU4Wd5I/olR0QfOID650/OdddNlJ8X597dt91z7md2jld2D1X8X+vzTPeeh92jq70tF9Z6qaFK8L7Q93YFvp8GoU/gaVHyPRkFWvpKitDTRCUfTwvqQ3U2jY3SmZ6lUg4Y3zqOVZZqOaJcLVEqlejrqxGEAWEYEkUh9f5+KtUK1WqVSrnMqgnG8xRFngMQBiG+7/WKW4VFa0Vff5VqJSKKtPB8IcLQl9VKKCOrRHJ+0ZUrkQt9baSWQkq520r19qonL6+W/Y8346LVbp/Pzy42H59a6h6eGJ243Tp7k1d0q/XB0RN3Pz7zkQPDw5dUFuSSAOCF5HqkBj6SCpWWrJoph+4fq4G7KcnyLUux+wOA7WN9Xze2cdtjYdrcqH31P/1Ae1Hoe1Hgy0ArIbEILPV6lT5f47pdhsZHWTc4SOPUNL6CTc/bhdWWSugTlUP8oFdZHYQe1WqZWq1KpVrGDzTlUkQQeGgte36klhRFTp73ghIlJUprrDEEnofne1hMr9jV95ASyijKicVOryAasZBJKnJbSK8vEp7vGyEQWok9wtivr3levRaW7x3ekLr9VbyPP944XisHD9ai4G3d2H7wofMrH2PzZjl1iQHwkuONrtyy5fn1oH1HlrTMfMd2U6d3nV7onr9sw8AfG2s/GHe6K5Vy+NelUmAqpVBJDL6ShL6HtTnDAzV2TYwzc89DqL4qtWqZhZOnuerVN1AZqmEoyLMCZwVh5ON5ilIppFQqo6RC+wrjLGEYoqQEa8nzgizLSNOUNM1YWWkSRSWwjjRJUQiMzenEbZTyKXKDMtB5ZJrZfzmGbRkaRU5QKTFfliTDVZzyWW7HdJPCtONU5YWjk5h/PtlMXtoj6PH97sAfVjxxYyfh6rvPLJ7/bEcha5uS+CpMUtWArJfyAV8a59BOS6+ilbgMoFr2/sWXxS8JJ35dIFFSSVcYnLWUw4BSmuPnFmsMnSLlshc+j3yuwZmPPciGndtRtRJR6DNQr1OuVunvr+N7AYjerEope2S27wUEXoBCkacFnU5CnhdYC572UVLRX68TeBopHEGg8UOPvoE+6v39lMOIKAjwlKKuQ6JcUiuVqA7VyfoD6qM1aiWPyIdyGOCsVaHvGd+Tha/tFVv71K9u7KP/2IGDhSH41Gzsrrn7zOL0pQi+S4OI/nyxSsmdoZSi0yVXAi0K82bgozg7WwrCwTb5oBQCJYQwGIIooByG9EuPxunzEHrkcU7TT4iUxtcR3ZlFZGuCuOQDPuO1Qc6cPIULPUqVMmmaoVSM7/torQmCAGt7KTLP88iyDCElJi8QCASuN+RaCDzPIwxDhIKwFNJYXMHTCj/Pue/R4ww9bzszi8uMjA0RVTWNJKYUp9g0x5oCJcD3fGWKgsjXA6pw70hSe8XEz/7sW+9Pkl954lIa1nbFfdV0YO+NEfYyLRxKCBl4GqXE5T2+xp30tJdrJa1wFokjCgPKUYjFIAbLjI4Pox85T/bYDOc++Bka84vU92xg9s7HOPF3/0I6s0LJKO7+8O0snpxmdHQUFfh4nkZqhed5GGMQQnwWjL3AJEIA1lqMMTgHnu4BLwhDhJQ9rVkIZCFoLjV56Oi9ROuGmHj5lWy8dgeZnyNx+Erh694X1hBqRRF3UdYhnUMLmYZSvsT3zK8A4mrwLuWl1ZeQBuzRrJ6SdekuzG+RiFy2ALFY1B9YH6ZzgS/WCSGsklIqwarTr+jYFG9rP6WioHXPFGlZsuP6/fjVgLHrL2PxzkdQf3o750arhKN9vPhrv4amKAjKIdXSIFmjtdowJMnzDGsVzoGUEmMMxhiyLCMvCgLfR2qJlr1OPJzl8QeOM3N+lm07tuMLn8r4EFv37WY+66AHy1T8EVqtLqqRY6QgCgKEaxJ3EoSUCGfxHeCcb5BWC/3S8UoweLTdXljTgP8GcuPqbl8L49YKtNKiMAVFYSTA8ePHjcCd0X7PF9JejzDGWDylCH0f5RxGKWZCqBqFObtIMFBhx03PY8833ExjMWXxjjNs1HW6SYJXjRir1Vl+eJpH7noYoXrN8NYasixFiN6EVQBjDK12i1K5RKlSRntej6yOSpisoNtqMvnSF7Np9xa27N7Cusu2kTqD5xxGSfA1OvIJQg/P9/GUR5YYisIhtY90EpVbfOMQDimgUlOqcqkGk5ccAHv7LQQItd4CmbEqyXKs5UW7h0pjQFFY+/ee5yGkc1LSAx1grMGTCjMXk64sse3GvRQjJU4/eoYzf/lJWiemKVcUwdYhyhvH+cxffZxP/d5fYB+b5/73fYiP/dGfMbJxjDzLydK0V3lte30m4BBCYK397Pc8r0dce55Hs9Nien6Oq158LeXRGoXKSUSGDCRSg+8pAl9R9nxKUvemOShFnhniOCctDHme44oCz0LJSZSxThnjlDKlSxl8lwQP+ETWaPf6/u92eTLcinPaibHS035mi/mV2HxifKxWlthvLnLjyuVAKgkoSTkMqFnBwtRZNj1vMzv3b2Vs31aIPM4/fJb26TnixQW23HAFl73qepI8ofXoNLO33cXcsSmuP3Az4ZYRsjQGT+DJXlbEuc/5fUVREEUReZ4TRRFhGNLtdGh3u2zctIlyrYpQilJQ6rkSgYftldUghaSIE7JugnG9gUmdbsbjpxcoLOAMJsmJLERSiI4xVkmlbcZH54vioQMgj62ZYP5NhmaBFU5YjLAIhfOkQwipAHxRflgqFSuBonAu7Sb4UlNSPtNT5xi9bAOb926jVI2Iaj6X33QVu978UlYSx+Kjs8RLy1TWVXje66/juq97KXkgIdRknZiaX6JwgiLNKWxOXmR0um2SJKXb7a5qQyiXyxhj6HQ6CF+zZftWSrUKWntEpTJBqUSgA8KwTBCW8IMIT3uo1cCm3lcj8AS+tjgHeWYhdRhjwVhs7gitRFlA2uXh4eHKiad2jvLZeN6XGg2Dc9aBxJjVyfS97xUAuXCZQjtPa3ytKAWakhacn5lmfOMoo5vWgZRUqlWWG01Sk7NlwxinR0vUijKP/s2nCLXP825+McfyB9n7n1+H9gIe/Mxd5PdH1HdtJMMg0xwnemPXhICiKIjjmFKphLxQuKAUUaWMUBJPe/ieR2YKbGEgLzDdBJ1Zkm6GiVNKUYRymqIwGJUgrYM8J80sGkcoBB6S3BoECA/ncvQbSt10tAIfuCgd+UUprC8DTvHvMVHhkgOgKYxXJAXWCoSTF0jiWYC4G1P1JEpKwkAxPNKHLXI2bp6gb7BKZgvy1XTZQLVOe2GFu27/OFe/4hrWX7aN+2/9CI//1cc486kHuOxlV7H+il145YDx523nkTvv48xDjzO4cQyvFuGMpT44SJZlzM3Nk6YplUqFMAxX6ZcAoRRKKpRSZFmGwZF1EzqNFo2ZeTwhSZotAt/vzTpstFicXUAqSdFJ8JE4Y1BCoJ3AYdHSoRDCAUa4r3FF+is3rubBjzw5yBRg9snyfxdS6PuL9s8eAHVhKSTgNg0PjxgTqLNLZ8/9W0fUl4wJvrDPVyk9bawly3KHVBTGIpAWYHRwOPJ9KZW0Lgo9fF9T7+8jCgOWl5ZYWloijjPanS5WOjou47IXP4/Ry7cQlwyT//mNbLl8N4snllh4/DwDpSp5luKHPiPbNpKHmqBURkmNtY4wLNNoNFlaWqJWq9FXq1GrVXtRsO8hpURrjbG213CepHRXGnSWlmlMz5B1ukTCY/nMLN25FUQrozu7QmexQS2K6I8iAgTKSXwhkEIhLAjnrJVSuCL7ntNpevIQ2CNQQG9twxM133qI/JL3rVp5NYA9nwOYA/CM6a6C7988m3LJaMDbbpuUcMQ69Nkg8lGdTBROxkVhH7JONQA8kV2jfMIis0UQBtrTHs4WWCQSQZbmLC40iJOYwhQMjw5QFJa0SKgFFbK8YKnm8Zaf/G7OnT/LR/7wL3nJt3wtXrnE8AicOHGSleVlRscGyPIuzWaT01PnUNqjUikTRgG+pymswfMDwiCkyAviuEuepnQWlxHdlHSlSbUU0V8qcer+R1heamClot3qEIUh5YE6BY7himZuRZGlOUZAhiDUHr6zFMYBanCLlB/SyNgpe+h4nt99+AvNqDsLydn2yhUXzPATN2bmIpgAOv8eJviSiYI3r1Z67Fw/cIUt0slmNxO5FSlOfe81L735H44dO+b2bh750bjb2u95vhuoVaWUkBUFjl4BqRZ+b9LAavFAtVztDZwMPJRTnHj0OHsmr2XiBZex89r94Ac8eNsdRCWfofExVppNHn7oIer9NZI0odNJOTM1zejYKPV6DaUkSioEDk8qWo0W3VYb0hyRZDTPzlAsNOnOLlDyA848cJz507MUqeLko2dot7qkWcFCu4tzApEXJN2ULDOrfcQQCEXgEA5Ew+bXI9wVZSkv04jvGJX6jX2o4SVn/uVJNJlbtXhfoOEacXvh34vIvuQyIVlezEoEzjlni6KwFCcPHz5s3jA5Wdd26Ws67TajY2OyMAWtZo5DkCYGISHUHoGvCCOP5cUO96w8xrp1IwwN11EqZXz3ZlRZszQ3zYqnGN21jvpgldOPPoYohYRRxNJSg9mZJbQnibsdWq0YKTVSSYwzvWXYaUraiYnbMWm7g4ciWVqmfX4Or1vgdROWzi9z+thZznctJ1dmyAwoaSlHjmq5YHm2Ra1eZjCUZG1Fo7BY4UhcQVVIIbEEUqxPnSN3xijrRKT0lUbJAsvPHOy1aYoD9DZHrfp29ksV/q4BkC81J6b3gDLHMWElzglT2OJbqhO7HmfpmNBe8tK40RiUQps8L9SjU+dJ4gJnDQhBKYrwcNRrVdavH6Rc9mm0u7QemWJkZYV1G4YwWEySkoc+DsdiNo0VgtLoIMvzc8SdmFYzY2mpQ6XkMb8Us9zs0Gy3GUyqZHlBpxWjrMMkGd1mG5OkeElBe36ZKDGYTsHU4zNMTc8w27Y8lFqmrSPFoZyjnDomuhmbaiHGdrDGUpWKJejNsraOzDrQkpLNXckJAUKlAtN2hY21//3kFId62s7/28FogMV4+inwW2s0DF96aLkFMMJ70BZxbJxLzqyYD4rGQzlAnsWvW1puuG6CW5paoJMaktyR570EiqeL3iTS6QanppfYuWWYof6IOCs4e24eYy39fRX6qmWUBKkkzjokveXWyhparZQ0M0xPzzM60s+5c3MkaUq3nbI836QUBnQ7LaRxxK02MjfoxBAvtvAtzB4/z7GpRR5aaNFSHmexLDp7kS8myJyjmxR0szabKhGBsBjjcMKhLdSdxhOS1BoUShgHGVitlOq6Yu5kknzmIMhDYK+Moq+xHfF9DXj1FKTPxpyxvsRYaPHxe44vPn/7yDnnVrduOMc3vfrVm+bO3//1y40OifFUJ7W0E0Nqe/4fDlya98awSclca4VGWrBzwwDlUCKdI0sMjb4OQ/1lRkYHcThMYfC1R1akCOdoNhKWlrtU64OkmWN6Zokg8FlaaJK3OoRaowCXFRRJBkmGWWoRGUHz7DwnpxsczR0zUpFZR+ocJcAiKVZ3vxsJHSM47SymmzEqoCQ9cDnC9kgL6wp8V4BQtKXDKiEKa5znRLQtCNYdStPjPeJPKU/JRrtXMZM8hbSdWIuCvzxtZApjzwjhloEcIO0uvDZN80q3oLBC6m6ek9ji4t66Hsvqert3EYKT822S3DBW9+mPPLLM0W7FFFlOq9XF8zTW9BrG4zyDwnL23CLLK13MyXPMzZbIUsfyyhJTlZB6EKCsw9oCcgPdjLzZRjUTXOFYbBecymHBGMZ0SDtPKBzkAnIsGkHO6q4S4UgRnDMFgdIEnsMVghiHkAWRcYRK97qwXC9LIoS2COvnqa2Nj4+XoiTx7lte/nPgz5+GqXVrGpAvWRUtjhyB3PHPAvHSz5quLPYb7Yw416RJTFL0RtviekvR3ec9V7eqSxUzKwlJWtAse9Qjgy8ti4sr9FV73W7CWoq8IM9zGs2EuVYMnk9zPqbRmGO8f5Ckk3Hy+Hn6KwGh05gkxyQpMskpIxFOsJQ5zqeOprUMK8muUonZRk4HQ4wgcY5Y9Kb4CycwOERvajRtawlthnGSFItYzR0n9O4rBZrOGSmszpw7epriru3nzwd+jxeUkz2C+ks2rF8w2buqQ/9VSv9jDzWm734KmZX/eAA8cqSHJF/7dzuVvxZ6m+vzNMnjTkynnfSahJQgtw4lVS97vLpf1zl3UUoPEJrluKCTWTqpox55tDoZC4sdwjBES4UzBmehaz3muw4hE3ylUNpjpdkkKRzFUopo5vRJiSsMnpAo4dFEMxcnLKYZHoKNAtZZwxWDZc7GKyynlhkBTSHwVovNUiewQpDg6NVnC2xuEFIhrUQKQSwEmTNOCGEKEIXUupBiCbgHa+Txzy1X58hTANGFoUa5VX860idbNL5s6u4/rAl2AIWVpxD6AnNPUuR1hKVc0Qg0SZwiZS9P69wXc3YMYHs0jXHMtFJaaUF/KaSsPMiht2FLkViYb7TJTM764RLrR/oZrpcZrlQ5cvsDLHQzUiEpaYWnBJ6QZCannXcxFvqFZATLVmBbINk7VmVrUzHdgIdyxxkcAkeOwK26CjmgEQxpj0ElmckdXWExQmIdzpOeyJ3VDkDIs6mWLzgTx+f/lX6cAzjRmZ070VkzwV/2QWWJPS+0nvqsYyjUXt+TDJUqdNsJzRiQEuUsxvUMsHVP8kHOfe6shKCd5bSzHE9KfKmQQiCdI7cFnuhNuFq3boAN/WVGh2vsGRtj4dEp7j3TZNkY5tMc1dtpjgYCKagJRR+GLQKeF2n2D2qGrt+OKrfZdPcUdkUT5zmxgIYQKNFzETQC1auAZtQLWMg6FEIChTNCikTIRmrMrzv0fufEzJk4nr5gSvkKBwGsAfDLRMIPT08v71w/srQdgu0330w2/cjVWiv8KJBJO0Gszm/5/BkfvefrvohKvPB9IQS5s+TGggMlBCVPEWhN4FkCXzLQX6Z/sEp9qI++Ush4qYAkJjYZAlBC4gMlIRhAsEFILgsDdo1oNr3iKvrf8d9JH7yD4ld+iU33N1le9uhmKa3Vs7dO9m5UQmoL2lagpUdeGCOllF0pP7iSZ2+fhxnI1ZbQH6LTI56/QhC5tXrAp3bN1ll3ulku1zcODg4I2F5YR+Rr4XkShENIAcLhXA98vY2a4ot+XQxEwed/XypB4CuUcNSrEZfv30GtL2Ji4zhjE4OU8oxhqfDp5cikc3hIQiGp+QETtRoTwwOEG8aQ11+H3ngF3o6rUNsvoz42xli9n6FyjboXUZG9WTVSgnOWsi+IyppQaXIgFgLj5K/Pw8x2CABzstOZBdz+oPpP+3X1/astXPqLaDi5xgN+ZWIBYpn+zVynk6h2e9A6a6RAB9pRKfnoFYHpqUGUFqv212IRq2AU4MBavkAjitXVqj2KozccUgmBkD1Cenx0mI2b1vH4iUepj9bZfeUuHvn0CUJPMR0ntJwFema76STnbYcgdujGMuUVTe09f0phc+KPfYzGR+7l2GzOXTmcc7AoBG0cBoGTvf1xE9UKoyMlFtNlTIHKnMWz6iQgjkO2NQw3ekIUj8TxtLb8kUT4ALeBEU+u4daI6GfCDJ8921wCaDSbw90sR0iHpwR9tRB/1pE7hxW9od9ZVuCsw30eNdOjMXpYdJ93LAKLEAIJBF5P+1kM5WqIw9LJekPFrSfZtGs969bXaTU7jJcC8k5C162O9XKQ4GgIwRkruK9V0LznNEP/759ZfOAhlpczHisEc0jaWFLRu25PKHCCUDhKShPWStSHMrx2RmZlRhCmk2mmjoA1STJ3YpVmuTtv/f5Fqs5dZI4lYHfVBq8BOfhIc/5D/1Y0y3PRBAO4m7dvDwAhAlHujW6UDhzrRgeohpJAyh5dgiX0dK+ok950UeUcSoBenTaqLtSri9X/Xw0+fCUJvNXRvhSEnkegA86dW2KpYWkud/FCj7GNfQyUS2ysh4TOUfZDlAMlHAWwKOCUgLut4vYuPHq6w2eWNZ9OFY/hsQh0BCSudyROSaQzDAlB0mmz3O4SRZ5Z31+xTcx/Op42H1/l9uxUL8Px2VrAJ9QDuov/1CqYRYln1RQFdYkCUB9fWsoB1o/Uf725srhfaWUrkS9rlQDjYHGpjR8EmKJACNBSIAVIqVanF6xGJs6tmuWL/g4gEVRLAaEn0AqsLZgYGWF+MePWD93FkTtP8OAjZxkolSiJguWFFtXII44zWllvwFFR5CgEzklS6bACGtZhA48z3TbnrKGBI3WCDIkTIIUkxhJYy/P6y/T5mvLEAM24Q3+1T5aD8HzabAc7+/tfP50kd65qMQFwDNxFzUne6tdna/zmk1ZzMenMsdYV95Vp7Bfu3vJ/r9y2cevuzcPvijuLr2u0Ok5aJ9evG8IUGSP9dbpJSrOTINSFQMJiBRjrcO5zuREhBEpJtKd63OEq9TE4UCH0HL7XK6cvlwL8qMY/3fUozW5CN8s5fnaBc9NLTF65mc7SIu1mwsbxflYabTqZI/J8TFEgBQgkmYPCOaySzKUpbWtxQqBwOCHIpKKLxbeWyS0TbKlGjI73kweKmWZH4GBiuP6Ciu99w1DJe8VEtaxONNofPQDqAvAmQU+B3Vsu/96ECn5vtsh+FT5vfqL8ctpv06ZNYb1e141Go1gD4BOi32v27t1Qk53fzdL2qxaXl7Y2m02nlBb1vghbpKyfGGGsv8r60UG01jSaCXnhQCmEMHha4mmBpyX+an2gVpLCWExu8H3J2HCdvnKAswWep0iSlP76AKfPLdHJitVZ0QKlFHOLDcYH6gyVNJ1mk6GSx+ahKt3MEXcTPCVJjO1RK0oilaAoLB3rKFRP9RopiLEoLFukx/NqPnvWD2LzLkme08gKMu3RTFOWWyu2sNYk3a6NU66cipNfPdbLfAiAVXLUDUi/iVDxfJF+6AnBx5c1vdVq1SuKQrbb7XwNgJ/LV4oj4Pbu2b6x01q55czcgl3u5ijpy6F6lfHROp1mm7RI2b1jE/1lTTlURGFAlqZ0OymFtatH0XPRnbWrzeaG/nLAzs3jrB+tUvahSFNKYUhW5GitEDLkzOwKTigcvYIG53qqZX5+hSt3bKaiCkrliEolZKAaMlCuMFAKGCr5eM6S5xmJsaTG9AojrEMC2lrGnOBKz+eFG8fYsm0dK8kK/WNDzK0so8shqhwRm4LlTkd0EoMrrOxmxf3nsuL3nhBMOIBFk59aBd/TDjSazWbxbwG+SwqAqwv4xGte/8bG4tnHvjntdIZRkkgrUan69NdLVMtlFhpNOt0O9XqN8ZEh+ish68YHGRvtwxOKPEmJPI/A9yhHPutH6lyxZyP7d64n8sBkHSQFvu8RhhGtZpN6vZ+F5ZTlOOlFKtjPkt1KSZa6GdvXj7FpvIyTiqhUQYociaVe8tkyVmfjcI31fRUmwoABAX2+x+5ahU1Sct26QfYN1clzy0MrK5yYm6EyWMF4jrBepTRQ75HjOBrdFJM7UxhUIeWh6TS/84LZfaLFmAQ19SyIdJ8zPuCBAwfUH/zBH+Q71o280CTp3maW2VIYyHKgUM4y3N/PYH+d2bl5Tp+dITeG4eEqE+MDTIz1sXf7OLu3jrJz6xBX7tnEZVvH2LphgEBldFoNsjSnXK3heZrA88mzHJMXBFGV4+cWKJwAYXqOlBSrJLfAOEdJCfbv3cTS4hKBlPQP9NPuttAKgkBRKpXIkgSVG/rCkMHIY8e6cZbm50mEoC0F57pdusBV1+5lx+7NBJUSqlqmlSYY64jTnJVO6uK4EB2rukmqf3jepCtTT25a3bMdfJccAI8dOyYBNzE0clIr8Z0rnQZKCNFfqVAtlQhDRX8tYnRkhKwwrDS7zCw0mJ6eo9uJsUWBloJK5JN22uRxQqfVJc+gVK1hba8QABwmMzQaLer1fs4sdphrtBFK9qJmWB3N4ZBC4ISg0Whx5f5dKCymyKkP9uN7AdLToBWFKCj1lxElny45YTWim2W0jaM23M/Auj6GRqpIm7Fj71Y6IiGXmmY3ZrnVoRPnLDc6rLQz2zFSdZ3+xoc6zX9ZPcNLbjr+pRoFu4Mg3zu3ML1huL/sKV4Ud7pG+b5EgNaOJG3jeZotmzcgpeKxR0/hBx6dJGZmvsHsYoNOkhFEJecFIUHk24GBAWEdohtndDpduklMK06wOAqneGhqDit7lSriswDs5ZWVECAVcWGQJmPnxnHmlxcIahUa7YRHTk5RHhggFQ6jJTIIsEpQG6kzNDZEZlKivoDySBmvGjG/uEIrTokGapyenaW5HBMnBbMrLZpxbuLEqK7Qf3NsufETq6bXwNpwon9TX/DAAdQHb298ePPEyI1FGm/tpoURIJ11aE+DUJw8cYblxQb79mxn84ZxtPYoVSs0OzknTs1wbm5ZxKkV3TiR0zOzIklSh0XEpqCd5qSJob9colN4TM2toFYBhwAtJL7SZNascnc9WmdpqcU1e7bTTToUAlZabbpZFxFGGBFwZnqB6cUlcilpxylnzs8xM79EM8uRUUTuBM4LacQxTnvML3VotRJa3YR2YVnppi62SqYq+vqFTmd+6hKeC3gpp+LYc7injPxS9F91ue+u7soScVYgWjFpnrvF5S71Wo2xsUG33EmYPj/v4tyKpWZDrKx0XJy4drvTete5mWQmCsTNQeB/0+gQolIKXZKkIvQjlhZarBsZpttofzaLv5pC7r25UvZ4j9VqB60VzbRgdmmFWuTT6nQp1yoEeUahA449fppWs834yBhzKxlLjYZN2l0pC0uYOtdkllpfJGrVKimS0+cXyK0gKSxxbmnEad4tnGeU/sOHZ2cfuGi8Bmsa8N9BC05Oom//5OLMxPBgv3D5C7txN0NplWdWRKWKUFqK87OzYrnZEe1OKhdWEtFNnChAWEQgtDeRFPzW8fnObw2Uy58x1r3F9yVFUdDt5KLZ7DI0NMjj04u0ur0C1wsNTp5UREFAN8tWkykOJXtc4viAz4b1g3TaXdqdLsoLmFuJOXlmmrHxcR47Oe1On1twSVFIt7rKoaAQcW7EUqNrV9ptk2RGxMaIOIdubt1yp1t0UuPlwptheN2r5ufni2OXuOa7pDXganm+AeRQTR+ap297btzrWq0OURQszy83ygsrrrB5MVsY2y0KewQRfMAJ17ZFXBipbtJS/WIosq/bMlTduNRsPhaVh74pL+z7EcLkhVVaKhaXmnTj5LOaT6zSuVIJlCc/l0lxYEUPDwtLHfI4Iy8MaZJTrVc5fWaKiYlxpmfmSPNcDI4OiSROHkziZG+mHEK4ji6s8D2vlLeNLIoU5enCSimzLJW5xbN+dL8n1NvvP3as/VSyGWsA/Deqjv7I0RMNEK+/YvuGH47bzVtia36yudy+W6b5Qia9AXwfpSqZDMMzZ8+ejVfbmO7eOhjcI7T/hyp2vx6Vo3dNTU3/WXn7+KOeL3cqT1nf07LVinu54dUvh8BaR+BptJJowNMKYSyFc0gJeWFZWW7jpEZ70Gq18b3eLIdON6Z/cHB5abn9f5Zb+ZKEtJDmviIuzkFGKVCXBWHwdc6YN3gp64SvMegZqfUf2z556P5HFlpPsYpFcYmYZ/EceIku3IObvPrqobml+Su14ej9p08vf5G/J1YPKN8yUH5FU3Q+NRQOvLJI8sP1SB4eGK69udXpWmeQS60Mr1zh+MnzSE/0di0VlnWDffTXazx64gxoiVASkxvKnuK6vRtZV/fwfIUxhnacklvBwvyKzVInG53iI0tJ8cFABnc93mj885Pd0PaBgfW+li+Wvp5Wg6P33nvvvSsXpyO/zLP4ciM4xLOJtnkuAJALpUhPcMovRIjii+RAP3uY69evj/pIH3Rpxx8eqY8XJpNBEPLYqTkGR4axznHy9Hk6uWN0sEpZGPrrdUrVKnfe9yiJcZSV4Jrdm5moSyaGy1iT45Sm1c3IrWB2eoFWpzBzK7GSYeVXHp5Z/P8mQa9meOxF2QvxxDbK1XuzX8bsfjYi3lGq/gDau/2x5tIdz5a6v+daOdYXktSrh7BzvDJUGRy3T6GSwwFqzx68xx9vFuMDtQPWJntLoW9LUSSV5yC3rKwsMTxYYXhgCCkEwwM+nhAsLzWZGKywad0wlUBz/b6tDIWSep+m3h9QLpcJ/QApJHlRIKRySysdUQhtVan/jXMrK92pL5xceiF7ISdBXQviWO/e7FOs69R7Au/P0XJLOtD/669sNNxF/1ZsgrAe9K1vmHTl2aJ8NM8dEYAtnNzsso4F7voyb78ETL44cPWGwXw08NVdgQiu97REWMPYQB+6EFibEjdX0LpCPYANQ/2k3RyXGdJOC4+C3WODhKZL4DmGBocp+5JatYbnRUydnaEb5/jKs77Sqlr2/+XcwmIFmP8S12aPPHWtdWEClt3neR8OlX/TfF5smZqaSqZWgbkH/GOQ1YO+/2Gl2Al8wySoL9ewzlpF9L8iMlEy0zbb+RRcDAfQF1QWSoH/Spvnw5VyWQzU+7B5yqaJQbZsGGK0v8aOLRP0lwX9UcH6oYANYxUGapLt24Z5wTV7GO2P0DJn375trBvupxqVqIQBylmEsdRKNfIkc6HvEXr+KQ1vmZyclM+AFhIHQB4Gc5kX/IxW+oq2s9dPpempi14+dQyy0TIjRhcvtUX20/TMvF2bks8z36yUi8pjnvYueyo50u0QON8JX6oX5mm6L/CUxVqptWLjxDj1epm+esDV+3ewc/MEY/1V9u3awvOv3MH2DYMM1iKufcEerrhiC7v2rGf7tk2UgogiKyiHZZwTtJtdXJZj8lxqT2KtvUxpvqndbvtP8FGfrk8urgZ9GGGu0MEfj3j6hxPp/8jDcfyp1fVdF/Ynm4mAl2935bvL+Lc/mHfvnXwW5Y+faxpQnT17NhaIbTuG6/su+HlPdrAHQfjgTJZuUUKey/I0LpUiubS04gYH6tRLAXGzSS0K2LltA9WKz9BAjZ07NzPQHzE2Umd4sI/xkWEG+6v0VSLGRoYJg4B2q4UAotDr7QqJE/woIo5zkiwLTJ7/6GtfezR5kuDo6XB77ijku5R8XajENzWdfVcRqvdPgj4KxSRoB24MLtskS3+jlF6yMvrF1cDHrO0J4auyznAVaPZB31cDq982T3awh3r9E1ncMZ9ud7p3ZLk8Eaf2wZVGR6Sxc+1GzNzsAp7WCGFx1hAEmr5qhW6rTafVRkuJsJbWSoN2o0meZlgDK8stzp+fJ4kFrY5hem6Fc7NNMTPf7szONQ729ddHDx36XC/HhbPYPlYZfoq+rtoKfXu84Fv7lH5/x+a/dHcc/8TxpaXmql8njkAhwG1SwXuGRRQ2YvNdd7amF0eeZa2Z6rkEwNWo0Q1Vy/VCuLGlVnzf9oFofRR5tVZctJ5o7rYNjV+tXbHdCTG4vNx6Z5Hm9SyzL5qdWRZFYUQhHIuNDrVSjfZSl1YrocgdRQbnzs5SCqoII5mbmSdLCqbPtfjM0YdwFpQL+eht93J+vk2n3WG52cUJrauVaItU3pbzjdYfr/ZyADBeqQwKJV7X6Gb3rAaH9ou8ZHoKzJgK/sd64X4pQ529O8/eOAli6qJWzK3l8sgG+JmS8t7YDNS3HY0bf/NFqCr1pX7fGgCfPhVDvRZ2cfLNS63u31f7wnVK8LKVTn509X4/e0hD1fKPB8qN95dLN0d+Ho72VX9qZq5pXvaifXp5sUFjucv0+Sanjs8wVOnjsRPTfPL2B4hThx+GPHj3ce45+hi+79Ft5Xz8n++ludBBBT5LZ+bZv2MTsysdylqxfuM4RRabQMmNncJ9ZK7d/bvhXsUygBvt0y9WiOGxbnbf/OrcwyezWNcC7SDYMursz3lKDZzOkpc14OzURX5hl77aOpEfWa+8186T/fTRTuf/TIL++88HnwTcltrgNdvSeOb8vxMAn2s+YC+yPbc0q6QqJiaqg7ZhGr6nr981OFi96C3vDT4Q4lYpebCk7AsD5C+sG6y5mofevaWfl127h7Mnlrly2zpe/rzLuO+RKfIk48DLX0BzfpFHH5wm8jxuvO5yTjx0lgfuPsXLrtjCW191AycemWYwCLn5RVcyWvXZMNpPWSFC7XutwjXazv4+9EanTa6egZL6KpzZNjtIsGOk8sYnC0omVyPefqt+LpL+9nmtvncK7r4o4LJHIR8X3R/bXJi9/X5EU/vvPwBq5CKzuwd8wG4rlb5DZelbj/YAr9YA+AzxgUchr1T7HvASdlhZDEkrLne6eP5FQYkFxPGZmSOxr/9lMc5mQ89/TAnpqqVIWJMzMVJGhYq+muYl1+9A5YaqL3jRtZu47qrdzJxfYOuWYW568XY2rR8lbrV48bWb2blrlBThJgYjhO1gTWL9QNv5VuvcbGLvy0PvJSdnFu+8wFseAbsHfCX5JmzhqjK43gn905s2bQqfAEJ5BIodROuk579xDnHg3k7nNw587n7kTipDe6X+8cu0/G+jlSpnbPF/T3Y6jxwGe8H0HuwtNswuw9tbs/qnZcK7nsIqrzUAPt178ly2RbtcnOvk97vCPIbJf/yiB30hHyq+YWr29HxsXq5V+PvNlUymuL9qr3TdYiPpFIKf9KRxLmu4wcBzAyXfDYxX2bd1jJqvnFSCsOIxOhC5gUg73/PIXYIfBSK2MYvLS3S7BY1uJlPUe06vtF/7wMm5+y7OxAC2O1y60dNqf1a4lwuhvl1p4Xtey78oWBAHe3+WVEn+ciHFd92ftT9wNXiHwd4MvgCrwuJ3tgj5rrL21CO2+IXb2itv780w/5z/eAjsLq2/a6AUfdxX+gOP0l448DnXZC0T8gyZYWltttuLkl8a1pSddI8HUt90kbP9WQAeA3F2efmBftvnt1J732zX/Ny56ZU3BLJ0uh27z6SxEQtTc0W3m2oV+TQWG3hF4kqBFHkc0zi3RN6OhUKwNLfsltOYVjdtnptvlk+fOi/nukUxo+LFTp7+9nKSnN++faAmklL1sbNnp68GeRRcOQpuFL2RXldqpa90ws2USv7nBQuHQF0ZVD5tnAzuby8fuBq8VdPJB3sT8FU9z/atj/zs3iz5w0/GxQ/eAp7oRcXuavCOQL5FR88f8txvpRS/9plO87/+exe2Phc1oH3F5ZdHpai0vNwJqjquhLZwbSVkfUuf97ZV4JmtQ0Pbt46ODh0GMwn6/kbjrtNww3SS3DHbMafPznfyebJ7zy62s2OnFvVSzm/Od7J7jz98xhw/eV4sZHZlYaFjjt39qHlkeiWZMbL10Okz5o4Hp8VUnL6mGXPXI2eb8kycHThf6JcdPb1wHqBa3VQZqFVeDbh4zx4B2EB5uxwIJ0UmhbRAudOpDABcvfrS7AzLb7SCACe/fRL01tUXaGelMnRFWPmhq7T3d5ul3okX+gu2eK8Dsfy5AgZxFPKBKFo3YrNfXqcjUikPr9EwX6XqnnUbhsayuP3dcbelvUDOiTw/FUbhdxtrZkqa9f1haCTyrMi7m0f7+l93tNO5E1CvfnWnOHYMM16KOh3Dxofnln6jL5A3n290WkfmG2+pSe3LvLj5+PmVpbtmm6+q+aUXmzQbmWp1v/9MO/19IfjmkwvprQ+24v8zUa2/ajG1zU/PLv3gcqOxALBny8YDxN1R6ZzSxrW0tYQi/vbBeu0dcZ5TWOf5SmGsDUC8b7nRPn8e2F2tDiC8bzsWN98wVyQnpsANg/xW4HHl/dgWaw5NSLs9liqbduJ3jqbZuw+tFjEcALUXRBT0TY6a4sguT+/sCnV8OtA/+Y44zn/z35kT1M9BALowKuvm7Pnne0rdIJXaON3ovqtSM3iefEWSuI5U5voTy8vfsq1eu6HI02v3jQ+F0qqPHj48+wDAkVPn/2DryMinAM646humT0+3gXS5PvQbnznXfmVm0j9Zgk/PJOad3YXkdR87u/TrgOtbcD8TO/UrgJzN7a15Zh4C+ImDyH/6s3372q3FyTTNm404/12ptf/w9HRj93jlh8rlwJ9bWbJSagQO4cTFqLCx9Pfj3K8B6YVMxveAezPY5yfp87eEASbw+Ydm83sfs8nvXlS+xa1gBbgrTfdHN0nZv+L5c4+12m8/3imaxy7xls5nbQDymmuu2bp/XT3ZPhS4XRP1P+uDq/aOl93V6ytuW1Xcv7Xq37e9Uhne2Ne3ZV0Q3HTlWP+5a7aMPX/b4OBNV4+PD32RoknxxazHwc8tfMY94e/t2bTpymq1OvjSPTv+cv9I/6e3Vkuv2jIyMrphcHBiQ12+7YW7x9zLr9xcbOiTbvt4n9s1WrHbx2puy7qRyy/8nk2Dg7ufjJbZpdTrXyb87pvL9cUX++F7LpqMKugVKqj169dHW7U++Aqt8wPlUrJfqZfDk651XfMBnykesO1c0/d1bJ0zRVFcW6n6Y1mWGwnOl3KPMMVl1ia/F1J8x7k0/WdbFN3OSutNE2XvL7XLrwWiTaXS2BMStO4JYDMHQT5hMPhn20eu3rlzCOjfUKvecvXY6Hs7zebVgdS/vpzbByoB/08VzdeUo/D3+2tlG7dbSiqNlKrnszl73Oro0QvB0tTi4sMXwHcQ5CBUr/Tkn28T8q+GtBfd2Vm55WNZ8u2r2rEA3IUqmeG5+d++BvfOjWFJn3P6J+835iOr0bNZA+BXAYCTk+gjR48u+H7lt/qiSIkiHo1894vCOCmtEoH2pJIoMJcLZ94G0LXyRygs46FXU2Sbbtg49oObxgZ/XgBb+/s3bu3v71t9VsGh1V80ODhYPQT2tslJuWF4eBvgrt0+UN0/MnQL4AZ9+/qXbt/0KRUvv6bPd69qteJIeHL7jvH+dyXd5kY/UL/TXw6Vr6Rodzv0VStOC5xQnjTo/zY1NZVc1HwkVpvyxSGwW6Po/dsdb7zM9ygqoVmBOw706vvsxdXhEyp4+bAx33yNH7GS5Y//S7f5swdAHf3imZY1APLMdMup6WTTTwov/Gtfep417jInEEmR4XkeqjdebTPO1beVvA/YJKlpJx63eV643P7QoJI/dNnE0EscsGOw+mcb+8LvBOwNW9f/zfaxyiDg9vSV/vEFQ0M7pu+4Y/Sa9SMff8c73hGE3fTmF+1c/zuXj46O1PL85itGB3aaPN3Y6rRdq92upt3OTxR5ek1eZCOh74lqueSSOBFBVHHGWpNkucpR//3k7MrfXiiluphaWtW0gSyyq4eDiHNKte9pLH/bMpxZ3YJuJ0EfBnNNqf8v9zvzwStUpO6GxVPwI+IL88BrUfBXSxqNqWLnFdd8oLPS2CisvVJgC2MLGfkBziKstU4KEVCYPdVS9Ibc2Bttnvu5sQNVT/rbRqq1s6fnwuu3jb2uru26mYXG6dft2fA/TSs+luVx+JrLNh1spenZzuLyrtc8b/vXf+bOO5tRs/WS1129Z9+9x6devaEaXadNpk4sNInTVNT6KkpIS1JkAwjCShRSLQUis862ktR20kKj/O87cX7xl59k5IY4COKevr6+XUXxuxvwrlv01L2ntH79Q3H84QtuwNXgfRKKHb7/pnV5/hN7fE+ekyz+Rdy57owpPk4vC+KeTVszn7MABMTU1JRbaHf/cjgMvUiIG401BQKppMRkhZBSYvLCeFo5jYjiOJUruXFSw4bAEwsr6YvW1X21rlbqPz+38qqv2T0WLXQYy7uNF33jDXs2P3J2+Vpn0le//iV75V3Hpl456MTl1+7eJO56/MxIzVfebLMlTi01hZawbt0ojXbT5dYoz/dEKfBEFEW20+3KhZW2tOjfPjnb+IlVEJknNiX9Jsg9qDsGlffSluZPPtrpfvNMkpyYBP2HqxNQz4PZHVWvGyyS37w8ULVER3ws6bx+wbmjV4N3/qLP3Tk6umWx0/l37w3Rz2EAOkBMgj6y3Prxy/v7KoEz35cksSmFJeULjUsNHlLlucGXwkVRJIR1otVOOT7TomuMm5pfllrooKK94VgIKkpfX1ceVhg8R72/GtBurJC0Ylet+tz10KNifrFpC4NIXC62b5qgk3RxLqcwufCCCCEMvhYuLaycW2o8VFj1h6cXWz/LajHpE7STOgxme6gny0rtbWDfcbQT//pFvl4BqIPg/qQS3jCQZR+/WkfoMOSfVpZ+/ITlo6tZkwJQuxgsFZX8vxZx8SHg1L+3Nnwua0AAOdUDobwjSf9+wA/2RY59OGeEE9LLLZ5SGCxOWuFJSRmFdbCQdCk8X3TSgtOLKyzFmQtxYq7RcXPNxAkQD07NOuMs7VZXHDu7LFLpi+nFJnmpJjKTi4FqRBD65EVGbg2dNMOPQpQQdrCvLuZW2p882Wi/aqFZfPgJPt9nNd8xMFcTXTvklT/Rdea/HO12fvOWHqAudLzJAyB+E+yeXL53v5ab55Q8+2jOD30mT3/pAKiP9LI9agrMSOgd1ko/9mhr6c+fDdO1ntMmePXNthcGNaos//tQ62/xnevLe2tqhCgsTjicBxgDxqKUYPOWEUSWUfIj+ocG6GSJmJlpsGIy0bBSzM838MKyWGonYrmZMDoxwvRKm5HhQcKSx6ZNoxRFxlJzBecJ4ixB6gDroFKKXJIX8vxi69e+57/92D8dOXLkyQhhcQB4dHw8KpniDwLLez+VtH5hEvSff67KW7A6GX+LlP9jXxC9PZfB7J/GzRecLtJ/PgjyN1cDkyNQ7FLh/9FSXjXUbXzH5l51jVlrTP/quRbFFt/fKYzZcMKYT6wnWH+W9Pguz/umspbvw7NGKKVdkhNpQSouDLqSuCJjdLhGt5PhLGzZuoXjU2cYqvdTCMvMwhKjfVWqpYA0L+irVlheXmRi3QQ4wd0PPsy2Hes5f34eFfgUwhGnKUGpRCfOUNo3S+1ExFa+5ux884NfZJSGANz2gaH/z+Tp359stR59grns/dwf2BPkjXfu87wDSvudO7P8pY8V8R23gPduyC8ULexDfletVPmtRWEuf6TTuf/ZMr5DPkcBWAAiFPIDVaE+sh35UCDMg1uQb30kz/9fbN17w0JonRSFRiCFRDjwAx/PU0gt6SYZTkkym7PcWCbLEsp9Pp4S+MqxcdMIzeYi5ZLEuIRGa4UiazM9e5aoEpBmGUJCpVrCmYJqJaJWLYOURaubqMLqvzo73/zggScHggLctoGBn7bOfOZkq/XoahGpu+jc5JZqdedGWdy1T6sDG6ISs0r83WNFfMck6HdDvtqglO9R6sBwKfytQrr3P9LpHHsyc78GwGfofvaAv7Vc3rdb6w+X83x/yRSmT8jNPtZ3wr4GYCnNfjAuxDmZWy3B5kKitMSZnCgMUFphAB1opC9JXYoIFXMri2Q2x0lHO25hBWSmIMkSqn1lhO/hlKNWL5FmCdW+CC0dldBn/fgwOGuTONe582aHhif+C71shXsSzWd2Dg19h7DyEyeWlz++6gtmF/mGGjDlJP8vQzYLhkoV7s3Tv37Yy/77RV1v8ggU67WerGj/D7rCveeOdusbDn7+KJA1GuYZ9/lKpeFyln900PE8z1krQRYCl+CWc8EfDSAP+ehPIuxfCE99q5RQKCW8QAnkqhb0NUWREwUBvqcQSuKFHn6giKIQISwjI/0oJShXIoLAxw88hkaGyU2OdRYsVPsqGJNTq5YJo5Dp2Xmz3LVWqPLb7j958uiBHi93MRjk1aDD+uB3SaR/fHnhfU9SryePQTGh9fUbhPcu39OVR4v4h2+Pk3e04qK56u8qwI7D7i06/IyQau5TcfeVB/ncdvQ1APJV2SUi/z7PO2NKv6Xk3DrhrBNOSIsQQhApxKu1ENuNs/Fj1v5+fylc0YLXWKzRgZKe17OG5SjEZjlaQF+ljBcq+molKpUSpVJArRLSP1ilVgupVUv4vqLWV0X7ksJkaKEpl0qAxfM9fN+n1ekUp2cbOnbeocdnF999NXgf+cLRGE6tXx+o2Cw+3lj4B54EoIC9Koi+d9xxOAxV9bRJv+Vokv/mRR124mpQ58Hulfp3I19vbCnxdTNZdmLkCz9vDYDP8ORUAdiyNXcKKd4SCRUKt7r8t7fb3hiBNMh7lnH/MJ/mn+4vReOBsNcK44rI86TGEvqaaqWErwWl0KdWKVGplghCTakcUKlElEse5XJArRbhBxIhLNYVeL5HEAS0mk36ygFeENBOczs1s6QW2ubRYHDDty0uLprzX8QHazabxUrWXXziXJtJ0KfA/nyJ8Q1G/VPN8zrLFf8ddzU6v38LeO9dBfNBkH8C5oog+OnhoPQds6RvurcT/+OzdaSvfI6NFLarB3VvIfTHLVJlwuWFwAgp8lzQiiXf7bT8BOAmQT/4ipu/J5fBJ0xudZbnRipBtRIyMtjHQH+VuNNCmhyXJShhqVRC6vUSng9RyaNerzE42L8KUI9SOSA3CZ6vGBgcoB1n7sxCw8000qZxpTc98sgjraewt/eJM/zkhUbzK/PwjwJfLx+1nf2fnlt+94WA4wLpfgjsVX7wh57wvndW83X3dbO/fTbPk76kMiGjo6Ph7Oxs90sd3mr7oUyV+uv5PL0qFGzwEFicKrA/MlXwOxfO9ghYDh+2xcjI1zlj7xF5Mio9bZLCqbIQhKUSpbSLc4YgCOkb6MOLAsqVCOjtkXMS/DAkLCxOKqxxeF6HifER0ixjfrnpZlcSlUn/rWeWlx98ivSHeyIYx/F3r/PcT4WBuinzg++f7XROXejzWNWQ6ggUlwfRH3tSvr5RpDc80sjvX80Tm7X5gM+AdDqd/Ck0p7tJUHeb/GjN8x7Ryn9RbMx0jHkvjl/c35sgcMG8uQOgbut0WkO18ie1ld+e55lsY61BiEq1xLp1w/glycTGUUbXD6N98LRkZGSQgYEBHII0y/ACnyjwsXmGlpokzTg+NVucnm+pbqEOTs21fvdfkXmQB0Ceh9plfulYydPbz3j2unuWm3+9muEoPptuhOLKoPRLVnvrFj314hPd7tRFeeK1Eb3/TvcmJpmURzhivpTWvGCiLh8YeJsU+W8ZklKpHJjR/pLasWU9mzaNUe2rIJSj3WoxP7+I1j4D/YNorcjzDM/XmDxnfmaR2cU2Z84t5Kfmm16nkHecmO+84KJ+ZPd0R69dG1TfFwn1/Dnbfe1DWfbYE0yqAszeSuXXIyfe2O1kk8dIj19UnLo2I/rfcp0rX3xw0QV+zH2Jnxd7h+qv9Uz6PknWV6qWilI5VIO1kqjVq0gtXbvTcZ1uRp4VtigMoa9kvV4TQeBhrKPRiu38Uof5pZZqFZyUYenmk9MLj/P0+LfPZjyuqtV/ryS8l3yiMX8N0HwC+CRgt9cGf8Sz2eVz7dZ3LkLr2T6W97msAZ+sskM81dFnF9JWVwwMXOts+gdKuD1KOoTCat8TBU4URY6UEgQUzuKsxdMapTRCONLc0EkshVOfkKH/jY9PL595moCQgN3a398nnDsYGqMN1UMPt6YXnwA+AYjN/f2v0EKtP7608J6nOMh8DYDPNODW12oDpUK9U3eXf+DijAFfwbDz7du3B9Hy7M971rxVCPoLHAbXFZ5/zmnV8j11r0EERWGvSPNsXWHMXZh8BYewyv/z00vd9+Hc0wXEav53oKZRv1tY+9fHVxb/+Eu9XKOjo6XZ2dnOv8LErwHwmZKrx8dL3bbd/1Br9tPPUH3bZ0Gzc3x8KMy6l0spk76SPnFkan6Bi30rIdhz2WVjUsau1bLp1NTpldVfL57m0EkBiG39/eukUN8jhPzHRxfn/umiWj73XNgLsiZPb/7yF2MJxCToL/Jz8a9kFwQgNw2MXLenVhv4D1KvyXOuJ/irCER10aKXL7YARqxlqdbkOUEfrT2GNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTNVmTZ7v8/6Qmf+3V4gcVAAAAAElFTkSuQmCC"));
}

struct {
    bool enableESP = false;
    bool AimSilent = false;
    bool AimSilent360 = false;
    bool autoswitch = false;

    bool downaimkill = false;
    bool resetguest = false;
    bool telekill = false;
    bool Aimkilltpv2 = false;
    bool Aimkillrotate = false;
    bool Aimkillrotatev2 = false;
    bool Aimkillrotatev3 = false;
    bool Aimkilltp = false;
    bool downplayer = false;
    bool highjump = false;
    bool medikitrun = false;
    bool ultraswitch = false;
    bool speedhackjoy = false;
    bool speedrun = false;
    bool cameraup = false;
    bool wallHack = false;
    bool teleportcar = false;
    bool doublegun = false;
    bool upplayerx = false;
    bool telehack = false;
    bool aimbody = false;
    bool TeleBeta = false;
    bool climbup = false;
    float FlyUp = 0.0f;
    int FlySpeed = 0;
    float vehicle_y = 0.0f;
    float vehicle_unY = 0.0f;
} MasterBool;

struct {
    bool enableAimbot = false;
    bool aimbotShoot = false;
    bool aimbotScope = false;
    bool Aimkill = false;
    bool Aimkill360 = false;
    bool teleprt = false;

    bool Aimkillrage = false;
    bool aimbot = false;
    bool SilentAim = false;
    bool aimbotbody = false;
    bool UnlimitedAmmo = false;
    bool norecoil = false;
    float aimbotFOV = 0.0f;
    float aimbotSmoothness = 20.0f;
    float speedValue = 0.0f;
    bool speedHack = false;
} pAimbotPlayer;

struct {
    bool espLine = false;
    bool espBox = false;
    bool espInfo = false;
    bool espHealth = false;
    bool DISC = false;
    bool espDrawFov = false;
    bool espTracker = false;
    bool espLineTracker = false;
    Color espColor = Color::White();
    Color espnameColor = Color::White();
    bool espNickName = false;
    int lineType = 0;
    int boxType = 0;
} pEspPlayer;

struct {
    bool speedHack = false;
    bool undergroundCatapult = false;
    bool catapultDistance = false;
} pMemoryTools;

using namespace std;

std::string LoggedInOwnerID = "";

bool showAnimation = false;
long long animationStartTime = 0;

int frameCount = 0;
float fpsValue = 0.0f;
long long lastFpsTime = 0;

long long getCurrentTimeMs() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::system_clock::now().time_since_epoch()
    ).count();
}

struct FeatureNotification {
    char name[64];
    bool enabled;
    long long startTime;
    bool active;
} currentNotification;

void showNotification(const char* name, bool enabled) {
    strcpy(currentNotification.name, name);
    currentNotification.enabled = enabled;
    currentNotification.startTime = getCurrentTimeMs();
    currentNotification.active = true;
}

// Called from Java to send owner ID

// Show toast from native
void ShowErrorToast(JNIEnv* env, const char* message) {
    jclass cls = env->FindClass("com/ashu/Login");
    if (!cls) return;

    jmethodID method = env->GetStaticMethodID(cls, "showToastFromNative", "(Landroid/content/Context;Ljava/lang/String;)V");
    if (!method) return;

    jfieldID contextField = env->GetStaticFieldID(cls, "globalContext", "Landroid/content/Context;");
    jobject context = env->GetStaticObjectField(cls, contextField);
    if (!context) return;

    jstring jMessage = env->NewStringUTF(message);
    env->CallStaticVoidMethod(cls, method, context, jMessage);
    env->DeleteLocalRef(jMessage);
}


extern "C"
JNIEXPORT void JNICALL
Java_com_ashu_Login_sendOwnerIDToNative(JNIEnv* env, jobject, jstring ownerId) {
    const char *nativeStr = env->GetStringUTFChars(ownerId, 0);
    LoggedInOwnerID = std::string(nativeStr);
    env->ReleaseStringUTFChars(ownerId, nativeStr);

    LOGD("🔒 Owner ID received from Java: %s", LoggedInOwnerID.c_str());

    if (LoggedInOwnerID == "8Z9qRQ2zph") {
    } else {
        LOGD("❌ Blocked features for unknown owner ID: %s", LoggedInOwnerID.c_str());
    }
}



extern "C"
JNIEXPORT void JNICALL
Java_com_ashu_Menu_Init(JNIEnv *env, jclass thiz) {
    startClient();
}

extern "C"
JNIEXPORT void JNICALL
Java_com_ashu_Menu_Functions(JNIEnv *env, jclass clazz) {
    Widget widget = Widget(env);
    widget.Tab("Functions");
    widget.Tab1("Functions");
    // ---------------- Aim Features ----------------
    widget.Category(OBFUSCATE("Aimbot Features"));
    widget.Switch(OBFUSCATE("Activate All"), 102);
    widget.Switch(OBFUSCATE("Silent Aim"), 103);
    widget.Switch(OBFUSCATE("Drag Headshot"), 1055);
    widget.Switch(OBFUSCATE("Sniper Auto Aim"), 500);
    widget.Switch(OBFUSCATE("Up Player"), 20);
    widget.Switch(OBFUSCATE("Show Fov"), 16);
    widget.SeekBar(OBFUSCATE("Adjust Headshot Rate"), 0, 100, "%", 104);

    // ---------------- ESP Features ----------------
    widget.Category(OBFUSCATE("ESP"));
    widget.Switch(OBFUSCATE("ESP Line"), 1);
    widget.Switch(OBFUSCATE("ESP Box"), 2);
    widget.Switch(OBFUSCATE("ESP Name"), 4);
    widget.Switch(OBFUSCATE("ESP Health"), 9);
}


extern "C"
JNIEXPORT void JNICALL
Java_com_ashu_Menu_ChangesID(JNIEnv *env, jclass clazz, jint id, jint value) {
    switch (id) {


        case 102: { // ENABLE ALL
            if (LoggedInOwnerID.find("8Z9qRQ2zph") != std::string::npos) {

                pAimbotPlayer.enableAimbot = !pAimbotPlayer.enableAimbot;
                SendFeatuere(101, pAimbotPlayer.enableAimbot);
                MasterBool.enableESP = !MasterBool.enableESP;
                SendFeatuere(3, MasterBool.enableESP);

                MasterBool.ultraswitch = !MasterBool.ultraswitch;
                SendFeatuere(212, MasterBool.ultraswitch);

                if (pAimbotPlayer.enableAimbot) {
                    showAnimation = true;
                    animationStartTime = getCurrentTimeMs();
                } else {
                    showAnimation = false;
                }
                showNotification("Activate All", pAimbotPlayer.enableAimbot);
            } else {
                ShowErrorToast(env, "VIP PANEL ALWAYS ON TOP ✅.   ");
                LOGD("❌ BLOCKED: Owner ID mismatch! Found: %s", LoggedInOwnerID.c_str());
            }
            break;
        }


        case 103:
            pAimbotPlayer.Aimkill = !pAimbotPlayer.Aimkill;
            SendFeatuere(103, pAimbotPlayer.Aimkill);
            showNotification("Silent Aim", pAimbotPlayer.Aimkill);
            break;
        case 1055:
            pAimbotPlayer.Aimkill360 = !pAimbotPlayer.Aimkill360;
            SendFeatuere(1055, pAimbotPlayer.Aimkill360);
            showNotification("Drag Headshot", pAimbotPlayer.Aimkill360);
            break;
        case 7581:
            pAimbotPlayer.Aimkillrage = !pAimbotPlayer.Aimkillrage;
            SendFeatuere(7581, pAimbotPlayer.Aimkillrage);
            break;
        case 104:
            pAimbotPlayer.aimbotFOV = value;
            SendFOV(104, value);
            break;

        case 105:
            pAimbotPlayer.aimbot = !pAimbotPlayer.aimbot;
            SendFeatuere(105, pAimbotPlayer.aimbot);
            break;

        case 106:
            pAimbotPlayer.norecoil = !pAimbotPlayer.norecoil;
            SendFeatuere(106, pAimbotPlayer.norecoil);
            break;

        case 107:
            pAimbotPlayer.aimbotSmoothness = value;
            SendFOV(107, value);
            break;
        case 1044:
            MasterBool.FlyUp = value;
            SendFOV(1044, value);
            break;
        case 1043:
            MasterBool.FlySpeed = value;
            SendFOV(1043, value);
            break;
        case 108:
            pAimbotPlayer.aimbotbody = !pAimbotPlayer.aimbotbody;
            SendFeatuere(108, pAimbotPlayer.aimbotbody);
            break;

        case 109:
            pAimbotPlayer.speedHack = !pAimbotPlayer.speedHack;
            SendFeatuere(109, pAimbotPlayer.speedHack);
            break;
        case 147:
            pAimbotPlayer.UnlimitedAmmo = !pAimbotPlayer.UnlimitedAmmo;
            SendFeatuere(147, pAimbotPlayer.UnlimitedAmmo);
            break;
        case 110:
            pAimbotPlayer.speedValue = value;
            SendFOV(110, value);
            break;

        case 111:
            pAimbotPlayer.SilentAim = !pAimbotPlayer.SilentAim;
            SendFeatuere(111, pAimbotPlayer.SilentAim);
            break;
        case 550:
            pAimbotPlayer.teleprt = !pAimbotPlayer.teleprt;
            SendFeatuere(550, pAimbotPlayer.teleprt);
            break;

        case 1:
            pEspPlayer.espLine = !pEspPlayer.espLine;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Line", pEspPlayer.espLine);
            break;

        case 2:
            pEspPlayer.espBox = !pEspPlayer.espBox;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Box", pEspPlayer.espBox);
            break;

        case 3:
            pEspPlayer.espHealth = !pEspPlayer.espHealth;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Health", pEspPlayer.espHealth);
            break;
        case 33333:
            pEspPlayer.DISC = !pEspPlayer.DISC;
            break;

        case 4:
            pEspPlayer.espNickName = !pEspPlayer.espNickName;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Name", pEspPlayer.espNickName);
            break;

        case 5:
            if (value == 0) {
                pEspPlayer.espColor = Color::White();
            } else if (value == 1) {
                pEspPlayer.espColor = Color::Green();
            } else if (value == 2) {
                pEspPlayer.espColor = Color::Blue();
            } else if (value == 3) {
                pEspPlayer.espColor = Color::Red();
            } else if (value == 4) {
                pEspPlayer.espColor = Color::Black();
            } else if (value == 5) {
                pEspPlayer.espColor = Color::Yellow();
            } else if (value == 6) {
                pEspPlayer.espColor = Color::Cyan();
            } else if (value == 7) {
                pEspPlayer.espColor = Color::Magenta();
            } else if (value == 8) {
                pEspPlayer.espColor = Color::Gray();
            } else if (value == 9) {
                pEspPlayer.espColor = Color::Purple();
            }
            break;

        case 6:
            if (value == 0) {
                pEspPlayer.lineType = value;
            } else if (value == 1) {
                pEspPlayer.lineType = value;
            } else if (value == 2) {
                pEspPlayer.lineType = value;
            }
            break;

        case 7:
            if (value == 0) {
                pEspPlayer.boxType = value;
            } else if (value == 1) {
                pEspPlayer.boxType = value;
            } else if (value == 2) {
                pEspPlayer.boxType = value;
            }
            break;

        case -2:
            pMemoryTools.catapultDistance = !pMemoryTools.catapultDistance;
            SendFeatuere(5, pMemoryTools.catapultDistance);
            break;

        case 16:
            pEspPlayer.espDrawFov = !pEspPlayer.espDrawFov;
            showNotification("Show Fov", pEspPlayer.espDrawFov);
            break;

        case 9:
            pEspPlayer.espHealth = !pEspPlayer.espHealth;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Health", pEspPlayer.espHealth);
            break;
        case 14:
            pEspPlayer.espTracker = !pEspPlayer.espTracker;
            break;
        case 144:
            pEspPlayer.espLineTracker = !pEspPlayer.espTracker;
            break;

        case 10:
            MasterBool.ultraswitch = !MasterBool.ultraswitch;
            SendFeatuere(10, MasterBool.ultraswitch);
            break;
        case 11:
            MasterBool.highjump = !MasterBool.highjump;
            SendFeatuere(11, MasterBool.highjump);
            break;
        case 12:
            MasterBool.resetguest = !MasterBool.resetguest;
            SendFeatuere(12, MasterBool.resetguest);
            break;

        case 13:
            MasterBool.medikitrun = !MasterBool.medikitrun;
            SendFeatuere(13, MasterBool.medikitrun);
            break;
        case 1111:
            MasterBool.cameraup = !MasterBool.cameraup;
            SendFeatuere(1111, MasterBool.cameraup);
            break;
        case 15:
            MasterBool.speedhackjoy = !MasterBool.speedhackjoy;
            SendFeatuere(15, MasterBool.speedhackjoy);
            break;
        case 17:
            MasterBool.doublegun = !MasterBool.doublegun;
            SendFeatuere(17, MasterBool.doublegun);
            break;
        case 166:
            MasterBool.wallHack = !MasterBool.wallHack;
            SendFeatuere(166, MasterBool.wallHack);
            break;
        case 19:
            MasterBool.telehack = !MasterBool.telehack;
            SendFeatuere(19, MasterBool.telehack);
            break;
        case 20:
            MasterBool.upplayerx = !MasterBool.upplayerx;
            SendFeatuere(20, MasterBool.upplayerx);
            showNotification("Up Player", MasterBool.upplayerx);
            break;
        case 21:
            MasterBool.aimbody = !MasterBool.aimbody;
            SendFeatuere(21, MasterBool.aimbody);
            break;
        case 22:
            MasterBool.AimSilent = !MasterBool.AimSilent;
            SendFeatuere(22, MasterBool.AimSilent);
            break;
        case 1056:
            MasterBool.AimSilent360 = !MasterBool.AimSilent360;
            SendFeatuere(1056, MasterBool.AimSilent360);
            break;
        case 500:
            MasterBool.Aimkilltp = !MasterBool.Aimkilltp;
            SendFeatuere(500, MasterBool.Aimkilltp);
            showNotification("Sniper Auto Aim", MasterBool.Aimkilltp);
            break;
        case 501:
            MasterBool.Aimkilltpv2 = !MasterBool.Aimkilltpv2;
            SendFeatuere(501, MasterBool.Aimkilltpv2);
            break;
        case 502:
            MasterBool.Aimkillrotate = !MasterBool.Aimkillrotate;
            SendFeatuere(502, MasterBool.Aimkillrotate);
            break;
        case 503:
            MasterBool.Aimkillrotatev2 = !MasterBool.Aimkillrotatev2;
            SendFeatuere(503, MasterBool.Aimkillrotatev2);
            break;
        case 504:
            MasterBool.downaimkill = !MasterBool.downaimkill;
            SendFeatuere(504, MasterBool.downaimkill);
            break;
        case 505:
            MasterBool.autoswitch = !MasterBool.autoswitch;
            SendFeatuere(505, MasterBool.autoswitch);
            break;

        case 506:
            MasterBool.Aimkillrotatev3 = !MasterBool.Aimkillrotatev3;
            SendFeatuere(506, MasterBool.Aimkillrotatev3);
            break;
        case 507:
            MasterBool.speedrun = !MasterBool.speedrun;
            SendFeatuere(507, MasterBool.speedrun);
            break;
        case 508:
            MasterBool.TeleBeta = !MasterBool.TeleBeta;
            SendFeatuere(508, MasterBool.TeleBeta);
            showNotification("Sniper Auto Aim", MasterBool.TeleBeta);
            break;
        case 509:
            MasterBool.climbup = !MasterBool.climbup;
            SendFeatuere(509, MasterBool.climbup);
            break;
    }
}

extern "C"
JNIEXPORT void JNICALL
Java_com_ashu_Menu_OnDrawLoad(JNIEnv *env, jclass clazz, jobject draw_view, jobject canvas) {
    DrawView draw = DrawView(env, draw_view, canvas);




    if (draw.isValid()) {
        // Real-time FPS Calculation and Drawing in Bottom-Left Corner
        long long currentTime = getCurrentTimeMs();
        frameCount++;
        if (currentTime - lastFpsTime >= 1000) {
            fpsValue = frameCount * 1000.0f / (currentTime - lastFpsTime);
            frameCount = 0;
            lastFpsTime = currentTime;
        }

        char fpsText[32];
        sprintf(fpsText, "FPS- %.0f", fpsValue);
        Vector2 fpsPos(30.0f, (float)draw.getHeight() - 40.0f);
        draw.DrawText(Color(0, 0, 0, 200), fpsText, Vector2(fpsPos.X + 2.0f, fpsPos.Y + 2.0f), 30.0f);
        draw.DrawText(Color::Cyan(), fpsText, fpsPos, 30.0f);

        if (pEspPlayer.espDrawFov) {
            // Draw a Purple circle with thicker line (4.0 thickness) at center of screen.
            // Radius scales dynamically with "Adjust Headshot Rate" (pAimbotPlayer.aimbotFOV: 0-100)
            float radius = 50.0f + (pAimbotPlayer.aimbotFOV * 4.0f);
            // Draw glowing outer layers
            draw.DrawCircle(Color(168, 85, 247, 35), 8.0f, Vector2(draw.getWidth() / 2, draw.getHeight() / 2), radius + 2.0f);
            draw.DrawCircle(Color(168, 85, 247, 75), 5.0f, Vector2(draw.getWidth() / 2, draw.getHeight() / 2), radius + 1.0f);
            // Main circle
            draw.DrawCircle(Color(168, 85, 247, 255), 4.0f, Vector2(draw.getWidth() / 2, draw.getHeight() / 2), radius);
        }

        // --- Premium Intro Animation ---
        if (showAnimation) {
            long long elapsed = getCurrentTimeMs() - animationStartTime;

            if (elapsed < 1200) {
                // Phase 1: Full black screen, center displays the skull logo
                draw.DrawBlackScreen(255);
                draw.DrawLogo(draw.getWidth() / 2, draw.getHeight() / 2, 180.0f, 180.0f, 255.0f);
            }
            else if (elapsed < 2400) {
                // Phase 2: Full black screen, logo disappears, bold purple text "VIP PANEL" at center
                draw.DrawBlackScreen(255);
                // Center bold text (size 70.0f)
                draw.DrawText(Color(0, 0, 0, 200), "VIP PANEL", Vector2(draw.getWidth() / 2 + 2, draw.getHeight() / 2 + 2), 70.0f);
                draw.DrawText(Color(168, 85, 247, 255), "VIP PANEL", Vector2(draw.getWidth() / 2, draw.getHeight() / 2), 70.0f);
            }
            else if (elapsed < 3800) {
                // Phase 3: Black screen fades to transparent, and "VIP PANEL" text slides from center to final top position
                float progress = (elapsed - 2400) / 1400.0f; // 0.0 to 1.0
                if (progress > 1.0f) progress = 1.0f;

                int screenAlpha = (int)(255 * (1.0f - progress));
                draw.DrawBlackScreen(screenAlpha);

                // Smoothly interpolate Y position from center to top (Y = 120)
                float startY = draw.getHeight() / 2.0f;
                float endY = 120.0f;
                float currentY = startY + (endY - startY) * progress;

                // Smoothly interpolate size from 70 to 45
                float currentSize = 70.0f + (45.0f - 70.0f) * progress;

                // Color interpolates
                Color currentColor = Color(168, 85, 247, 255);

                draw.DrawText(Color(0, 0, 0, 200), "VIP PANEL", Vector2(draw.getWidth() / 2 + 2, currentY + 2), currentSize);
                draw.DrawText(currentColor, "VIP PANEL", Vector2(draw.getWidth() / 2, currentY), currentSize);
            }
            else {
                // Animation finished!
                showAnimation = false;
            }
        }

        // Show "VIP PANEL" overlay when Activate All is ON and animation is not running
        if (pAimbotPlayer.enableAimbot && !showAnimation) {
            Vector2 welcomePos(draw.getWidth() / 2, 120);
            draw.DrawText(Color(0, 0, 0, 200), "VIP PANEL", Vector2(welcomePos.X + 2, welcomePos.Y + 2), 45.0f);
            draw.DrawText(Color(168, 85, 247, 255), "VIP PANEL", welcomePos, 45.0f);
        }

        if (pAimbotPlayer.enableAimbot) {
            Response response = getData(draw.getWidth(), draw.getHeight());

            if (response.Success) {
            for (int i = 0; i < response.PlayerCount; ++i) {
                PlayerData data = response.Players[i];

                Vector3 HeadLoc = data.headPosition;
                Vector3 PesLoc = data.bottomPlayerPosition;

                if (HeadLoc.Z < -1) continue;
                if (PesLoc.Z < -1) continue;

                float distance = data.distance;
                float health = data.health;
                bool IsCaido = data.isDieing;

                // Limit scale for ESP
                float scale = std::max(0.5f, std::min(1.0f, 500.0f / distance));

                // Calculate player box dimensions
                float boxHeight = abs(HeadLoc.Y - PesLoc.Y) * scale;
                float boxWidth = boxHeight * 0.50f;

                // Adjust position for head alignment
                Rect PlayerRect(HeadLoc.X - (boxWidth / 2), draw.getHeight() - HeadLoc.Y, boxWidth, boxHeight);

                if (pEspPlayer.espLine) {
                    Vector2 lineStart;
                    Vector2 lineEnd;

                    if (pEspPlayer.lineType == 0) {
                        lineStart = Vector2(draw.getWidth() / 2, 0);
                        lineEnd = Vector2(HeadLoc.X, draw.getHeight() - HeadLoc.Y);
                    } else if (pEspPlayer.lineType == 1) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight() / 2);
                        lineEnd = Vector2(HeadLoc.X, draw.getHeight() - HeadLoc.Y);
                    } else if (pEspPlayer.lineType == 2) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight());
                        lineEnd = Vector2(PesLoc.X, draw.getHeight() - PesLoc.Y);
                    }

                    if (IsCaido) {
                        draw.DrawLine(Color::Red(), 3.5f, lineStart, lineEnd);
                    } else {
                        draw.DrawLine(pEspPlayer.espColor, 3.5f, lineStart, lineEnd);
                    }
                }

                if (pEspPlayer.espBox) {
                    if (IsCaido) {
                        if (pEspPlayer.boxType == 0) {
                            // Draw red glowing border
                            Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                            draw.DrawBox(Color(255, 0, 0, 45), 5.5f, glowRect);
                            draw.DrawBox(Color::Red(), 2.5f, PlayerRect);
                        } else if (pEspPlayer.boxType == 1) {
                            draw.DrawBox3D(Color::Red(), 2.5f, PlayerRect, 10);
                        } else if (pEspPlayer.boxType == 2) {
                            draw.DrawCornerBox(Color::Red(), 2.5f, PlayerRect, 4, 4);
                        }
                    } else {
                        if (pEspPlayer.boxType == 0) {
                            // Draw customizable color glowing border
                            Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                            Color glowColor = pEspPlayer.espColor;
                            glowColor.a = 45;
                            draw.DrawBox(glowColor, 5.5f, glowRect);
                            draw.DrawBox(pEspPlayer.espColor, 2.5f, PlayerRect);
                        } else if (pEspPlayer.boxType == 1) {
                            draw.DrawBox3D(pEspPlayer.espColor, 2.5f, PlayerRect, 10);
                        } else if (pEspPlayer.boxType == 2) {
                            draw.DrawCornerBox(pEspPlayer.espColor, 2.5f, PlayerRect, 4, 4);
                        }
                    }
                }

                // ======= Draw Nickname =======
                if(pEspPlayer.espNickName)
                {
                    if (!IsCaido) {

                        Vector2 namePos(HeadLoc.X, draw.getHeight() - HeadLoc.Y - 20);
                        std::string playerName = data.name;
                        draw.DrawTextWithShadow(pEspPlayer.espColor, playerName.c_str(), namePos, 16, Vector2(2, 2), 0.5f);

                    }
                }
                // ======= Draw Distance =======
                if (pEspPlayer.DISC) {
                    float centerX = draw.getWidth() / 2.0f;
                    float centerY = draw.getHeight() / 2.0f;

                    if (!IsCaido) {
                        Vector2 namePos(PlayerRect.x + (PlayerRect.w / 2), PlayerRect.y - (5.0f * scale));
                        namePos.X -= (strlen(data.name) * 2.5f * scale);
                        float textSize = 12.0f * scale;
                        Vector2 shadowOffset(1.0f, 1.0f);
                        char distanceText[32];
                        sprintf(distanceText, "%dm", static_cast<int>(data.distance));

                        // Calculate centered position for distance text
                        float textWidth = strlen(distanceText) * 6.0f * scale; // Approximate text width
                        Vector2 distancePos(
                                PlayerRect.x + (PlayerRect.w / 2) - (textWidth / 2),
                                PlayerRect.y + PlayerRect.h + (18.0f * scale) // Increased from 12.0f to 18.0f to move it further down
                        );

                        // Draw black border
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X - 1, distancePos.Y), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X + 1, distancePos.Y), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X, distancePos.Y - 1), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X, distancePos.Y + 1), textSize, shadowOffset, 2.0f);

                        // Draw main text
                        draw.DrawTextWithShadow(Color(255, 255, 255, 255), distanceText, distancePos, textSize, shadowOffset, 2.0f);
                    }
                }





                // ======= Health Bar =======
                if (pEspPlayer.espHealth && !IsCaido) {
                    Vector2 healthBarPos(PlayerRect.x - 5.0f * scale, PlayerRect.y);
                    float healthBarHeight = boxHeight;
                    draw.DrawVerticalHealthBar(healthBarPos, healthBarHeight, 200.0f, data.health);
                }
            }
        } else {
            // Draw simulated mock players for testing preview when not connected to daemon
            int simulatedCount = 2;
            for (int i = 0; i < simulatedCount; ++i) {
                float headX, headY, bottomX, bottomY, distance, health;
                const char* name;

                if (i == 0) {
                    headX = draw.getWidth() * 0.70f;
                    headY = draw.getHeight() * 0.40f;
                    bottomX = draw.getWidth() * 0.70f;
                    bottomY = draw.getHeight() * 0.65f;
                    distance = 45.0f;
                    health = 200.0f;
                    name = "Training BOT 1";
                } else {
                    headX = draw.getWidth() * 0.30f;
                    headY = draw.getHeight() * 0.30f;
                    bottomX = draw.getWidth() * 0.30f;
                    bottomY = draw.getHeight() * 0.75f;
                    distance = 15.0f;
                    health = 100.0f;
                    name = "Training BOT 2";
                }

                float scale = std::max(0.5f, std::min(1.0f, 500.0f / distance));
                float boxHeight = abs(headY - bottomY) * scale;
                float boxWidth = boxHeight * 0.50f;

                Rect PlayerRect(headX - (boxWidth / 2), headY, boxWidth, boxHeight);

                if (pEspPlayer.espLine) {
                    Vector2 lineStart;
                    Vector2 lineEnd(headX, headY);

                    if (pEspPlayer.lineType == 0) {
                        lineStart = Vector2(draw.getWidth() / 2, 0);
                    } else if (pEspPlayer.lineType == 1) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight() / 2);
                    } else {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight());
                        lineEnd = Vector2(bottomX, bottomY);
                    }

                    draw.DrawLine(pEspPlayer.espColor, 3.5f, lineStart, lineEnd);
                }

                if (pEspPlayer.espBox) {
                    if (pEspPlayer.boxType == 0) {
                        // Draw customizable color glowing border
                        Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                        Color glowColor = pEspPlayer.espColor;
                        glowColor.a = 45;
                        draw.DrawBox(glowColor, 5.5f, glowRect);
                        draw.DrawBox(pEspPlayer.espColor, 2.5f, PlayerRect);
                    } else if (pEspPlayer.boxType == 1) {
                        draw.DrawBox3D(pEspPlayer.espColor, 2.5f, PlayerRect, 10);
                    } else if (pEspPlayer.boxType == 2) {
                        draw.DrawCornerBox(pEspPlayer.espColor, 2.5f, PlayerRect, 4, 4);
                    }
                }

                if (pEspPlayer.espNickName) {
                    Vector2 namePos(headX, headY - 20);
                    draw.DrawTextWithShadow(pEspPlayer.espColor, name, namePos, 16, Vector2(2, 2), 0.5f);
                }

                if (pEspPlayer.espHealth) {
                    Vector2 healthBarPos(PlayerRect.x - 5.0f * scale, PlayerRect.y);
                    float healthBarHeight = boxHeight;
                    draw.DrawVerticalHealthBar(healthBarPos, healthBarHeight, 200.0f, health);
                }
            }
        }
    }


        // --- Premium Bottom-Right Notification Toast ---
        if (currentNotification.active) {
            long long elapsed = currentTime - currentNotification.startTime;
            if (elapsed < 2500) {
                int alpha = 255;
                if (elapsed < 300) {
                    alpha = (int)(255 * (elapsed / 300.0f));
                } else if (elapsed > 2200) {
                    alpha = (int)(255 * ((2500 - elapsed) / 300.0f));
                }
                if (alpha < 0) alpha = 0;
                if (alpha > 255) alpha = 255;

                float toastWidth = 360.0f;
                float toastHeight = 85.0f;
                float toastX = (float)draw.getWidth() - toastWidth - 30.0f;
                float toastY = (float)draw.getHeight() - toastHeight - 50.0f;

                if (elapsed < 300) {
                    float progress = elapsed / 300.0f;
                    toastX = (float)draw.getWidth() - (toastWidth + 30.0f) * progress;
                } else if (elapsed > 2200) {
                    float progress = (2500 - elapsed) / 300.0f;
                    toastX = (float)draw.getWidth() - (toastWidth + 30.0f) * progress;
                }

                // 1. Draw card background (semi-transparent dark)
                draw.DrawFilledRectinfo(Color(20, 20, 20, (int)(alpha * 0.92f)), Rect(toastX, toastY, toastWidth, toastHeight));

                // 2. Draw card outline box (thin red border for gaming aesthetic)
                Color outlineColor = Color(204, 0, 0, alpha);
                draw.DrawBox(outlineColor, 1.5f, Rect(toastX, toastY, toastWidth, toastHeight));

                // 3. Draw thick left accent stripe
                draw.DrawFilledRectinfo(outlineColor, Rect(toastX, toastY, 6.0f, toastHeight));

                // 4. Draw Bell Emoji 🔔 on the left
                draw.DrawText(Color(255, 255, 255, alpha), "🔔", Vector2(toastX + 35.0f, toastY + 53.0f), 28.0f);

                // 5. Draw Title: "SYSTEM ALERT" in bold red (left-aligned)
                draw.DrawTextLeft(Color(0, 0, 0, (int)(alpha * 0.8f)), "SYSTEM ALERT", Vector2(toastX + 70.0f + 1.0f, toastY + 28.0f + 1.0f), 12.0f);
                draw.DrawTextLeft(outlineColor, "SYSTEM ALERT", Vector2(toastX + 70.0f, toastY + 28.0f), 12.0f);

                // 6. Draw Status Message: "[Feature] Enabled/Disabled" (left-aligned)
                char statusText[96];
                if (currentNotification.enabled) {
                    sprintf(statusText, "%s Enabled", currentNotification.name);
                } else {
                    sprintf(statusText, "%s Disabled", currentNotification.name);
                }

                Color textColor = currentNotification.enabled ? Color::Green() : Color::Red();
                textColor.a = alpha;

                draw.DrawTextLeft(Color(0, 0, 0, (int)(alpha * 0.8f)), statusText, Vector2(toastX + 70.0f + 1.0f, toastY + 58.0f + 1.0f), 18.0f);
                draw.DrawTextLeft(textColor, statusText, Vector2(toastX + 70.0f, toastY + 58.0f), 18.0f);
            } else {
                currentNotification.active = false;
            }
        }

        // ESP Line Tracker and Name Tracker removed as per user request

    }
}